### ISSUE TITLE
Animation of marker style attributes

### ISSUE THREAD

**Issue by mvaivre** [react-native-community/react-native-maps#223] opened 2016-05-12 13:17 UTC
I've successfully animated coordinate changes on my markers, and I would like to apply animated rotations also (on Android).
- It would be nice to support animation for other things than latitude / longitude!
- Also, is it still planned to find a workaround in order to avoid patching `AnimatedImplementation`?

Thanks a lot for this amazing library!

**Comment by perkola** [comment] 2016-08-01 07:45
Also interested in this. If not animate, is there any way to style the markers, like rotating using CSS transformations? 
setting `style={styles.marker}` has no effect for me.

**Comment by the-simian** [comment] 2016-08-24 05:39
You can wrap an image with the marker and rotate that

**Comment by carleryd** [comment] 2016-08-28 13:09
I've managed to animate the marker on iOS by having the Marker wrap an Animate.Image, however this does not work on Android, it silently fails to animate the wrapped Image...

**Comment by alexHlebnikov** [comment] 2016-08-28 18:04
There is no way to animate markers in Google Maps API. Markers in Google Maps are meant to be bitmap images, so they are not designed to be animated.

**Comment by carleryd** [comment] 2016-08-31 15:00
@alexHlebnikov Would it be possible to extend this library to achieve this? Maybe by introducing a scale property on the marker?

**Comment by alexHlebnikov** [comment] 2016-08-31 16:53
@carleryd nope, it's all relies to Google Maps, if the ability to animate markers will be introduced there, it comes avaliable in react-native-maps. 
Since there is no any way to animate markers in Google Maps, we can't do anything with it in react-native-maps.

**Comment by NicolaGenesin** [comment] 2017-02-03 16:53
@carleryd have you managed to create a workaround for google maps? if so could you share us some hint?

**Comment by neilakoh** [comment] 2017-03-22 07:57
@NicolaGenesin Hi . . I have managed to animate my marker using sprite images and loop through it. Here is the code.

```
          <MapView.Marker.Animated
            coordinate={coords}
            image={{uri: this.state.actionSprite}}
          >
          </MapView.Marker.Animated>
```

Here is what I did:

1. cut the sprite images
2. loop through the cut sprite images and store filenames in state
3. apply the state inside MapView.Marker image property

It workes; however, sometimes a bit slow . . Maybe this is not a good way to do it, if anyone here has a better way please share :)

**Comment by NicolaGenesin** [comment] 2017-03-22 15:14
My current solution is done by applying a style to an image:

```javascript
import { Image } from 'react-native';
```

Then

```javascript
<MapView.Marker
key={object.key}
coordinate={{
    latitude: object.latitude,
    longitude: object.longitude,
}}
>
<Image
    style={{
    width: 24,
    height: 24,
    transform: [
        { rotate: `${object.rotation}deg` }
    ]
    }}
    source={marker}
/>
</MapView.Marker>
```

**Comment by moritzschaefer** [comment] 2017-05-06 10:21
@NicolaGenesin this seems not to work on Android unfortunately..

**Comment by juergengunz** [comment] 2017-10-13 08:30
any news about this? on Mapview.Marker the rotation prop is working fine and is even animated when the value is changed but on Mapview.Marker.Animated it is not

**Comment by PhaelIshall** [comment] 2018-01-31 13:32
@mvaivre How did you animate the coordinate changes on the marker?

**Comment by alvelig** [comment] 2018-01-31 14:56
@PhaelIshall see https://github.com/react-community/react-native-maps/blob/master/example/examples/AnimatedMarkers.js

**Comment by christopherdro** [comment] 2019-01-17 09:21
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/react-native-community/react-native-maps/releases).

Thank you!

**Closed by christopherdro** 2019-01-17 09:21 UTC
Labels: enhancement, help wanted, question
