### ISSUE TITLE
Google Map Must move on location change

### ISSUE THREAD

**Issue by Mahaswami** [react-native-community/react-native-maps#1937] opened 2018-01-04 13:35 UTC
### Is this a bug report?

Yes

       When the showUsersLocation is enabled, on change of location the bule dot will move. But the map won't move. 
 
### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

   yes 
### Environment

    react-native: 0.45.0
    react: 16.0.0
    react-native-maps: 0.15.2

### Steps to Reproduce
(Write your steps here:)
1) Install the plugin. 
2)      Include the MapView
            <MapView 
                         provider={PROVIDER_GOOGLE}
                         region={this.state.mapRegion}
                         onRegionChange={this._handleMapRegionChange}
                         showsUserLocation = {true}
            >

### Expected Behavior
  Map must move along with blue button when ever the location changes

### Actual Behavior
Map is not moving along with blue dot

**Comment by siddushar** [comment] 2018-01-04 13:37
+1

**Comment by manju-ms** [comment] 2018-01-04 13:50
pull request #1508 resolves this issue, but it has not been merged yet? Is there any problem with the pull request or is there any other way of doing the above issue. If  we follow the pull request and build the app map is not efficient as before(It will struck on fast zoomin and zoomout).

**Comment by alvelig** [comment] 2018-01-05 03:15
Your example works as expected.

The correct property is `followsUserLocation` and according to the docs is iOS only. 

So that's not a bug, but an enhancement.

@manju-ms #1508 is not about it. It's only a listener that allows you to know that location has changed, but does not work as you expect.

**Comment by manju-ms** [comment] 2018-01-05 13:07
@alvelig followsUserLocation will work in the ios when we have ios Airmaps default given by plugin, but i need to followUserLocation in both android and ios using GoogleMap.

**Comment by RidaRidss** [comment] 2018-01-24 11:46
state = {
moveToUserLocation : true
 }

  _gotoCurrentLocation() {
    this.map.animateToRegion({
      latitude: this._userLocation().latitude,
      longitude: this._userLocation().longitude,
      latitudeDelta: 0.0059397161733585335,
      longitudeDelta: 0.005845874547958374
    });
  }

<View>
   <MapView
            ref={ref => {
              this.map = ref;
            }}
            onMapReady={() => {
              if (
                this.state.moveToUserLocation &&
                this.props.userLocation.data.coords &&
                this.props.userLocation.data.coords.latitude
              ) {
                this._gotoCurrentLocation();
                this.state.moveToUserLocation = false;
              }
            }}
            showsUserLocation
            onRegionChangeComplete={region => {
           console.log(region);
            }}
/>

  <ButtonView
            onPress={() => this._gotoCurrentLocation()}
            style={styles.spot}
          >
            <Image style={styles.spotImage} source={Images.centrelocation} />
          </ButtonView>

</View>

**Comment by manju-ms** [comment] 2018-02-09 07:35
@RidaRidss Thanks for your response. My requirement is when ever user changes location, the map should recenter automatically to his position as google maps works. But your code works only when user clicks the button,  it will recenter to user position ?

**Comment by RidaRidss** [comment] 2018-02-28 07:13
yes it will

**Comment by alvelig** [comment] 2018-03-04 19:24
#2032 closes this

**Comment by bramus** [comment] 2018-03-04 21:38
I don't think it should follow the user location by default but only when explicitly requested to do so. A prop for this could be named something like `userTrackingMode`.

MapKit (iOS) has the [`userTrackingMode` property](https://developer.apple.com/documentation/mapkit/mkmapview/1616208-usertrackingmode?language=objc) for this exact case. Possible values are `none` _(default)_, `follow`, and `followWithHeading`. 

Don't know if Google supports this though – as I can't [seem to find any method on the Google Documentation about this](https://developers.google.com/android/reference/com/google/android/gms/maps/GoogleMap) – but perhaps something can be worked out manually now that https://github.com/react-community/react-native-maps/pull/2032 got merged.

**Comment by alvelig** [comment] 2018-03-05 01:26
@bramus great investigation. Actually now it's implemented with followUserLocation prop and by  [mapView setRegion:region animated:YES];

**Comment by danikane** [comment] 2018-05-27 19:41
Well, for Android unfortunately you have to DIY, but it gives you greater control.
First the map:
```
        <MapView
          onUserLocationChange={this._setMyLocation}
          onRegionChangeComplete={region => this.setState({ region })}
          ref={ref => (this.map = ref)}
          showsUserLocation={this.state.showsUserLocation}
          followsUserLocation={this.state.followsUserLocation}
        >
```
State of course:
```
  state = {
    region: {},
    myLocation: {},
```

Then I put 2 buttons that control showing and following user location.

```
          <TouchableOpacity
            onPress={() => this.setState({ showsUserLocation: !showsUserLocation })}
          >
```
and 
```
          {showsUserLocation && myLocation ? (
            <TouchableOpacity
              onPress={() => {
                if (!followsUserLocation) {
                  this._gotoCurrentLocation();
                }
                this.setState({ followsUserLocation: !followsUserLocation });
              }}
            >
```

And finally the methods:
```
  _gotoCurrentLocation() {
    const { myLocation, region } = this.state;
    this.map.animateToRegion({
      latitude: myLocation.latitude,
      longitude: myLocation.longitude,
      latitudeDelta: region.latitudeDelta,
      longitudeDelta: region.longitudeDelta
    });
  }

  _setMyLocation = event => {
    const myLocation = event.nativeEvent.coordinate;
    this.setState({ myLocation });
    if (
      this.state.followsUserLocation &&
      this.state.myLocation.latitude &&
      this.state.myLocation.longitude
    ) {
      this._gotoCurrentLocation();
    }
  };
```

Hope this helps.

**Comment by rmrohitmonga** [comment] 2019-04-06 06:24
Try to pass the parameter "distanceFilter: 10" in watchPosition. Set to 0 to not filter locations. Defaults to 100m.

**Comment by rborn** [comment] 2019-06-19 06:58
Very old issue, and seems to have various solutions for it, closing.

**Closed by rborn** 2019-06-19 06:58 UTC
Labels: enhancement

**Comment by gandarain** [comment] 2019-12-01 03:50
Try this, put your marker in center of map, when user move the map, get the last location with onRegionChangeComplete. You can read the concept from this link

https://alizahid.dev/blog/keep-marker-in-center-and-move-map-around-it
