### ISSUE TITLE
[Android] Map with region controlled as state won't let you move the map

### ISSUE THREAD

**Issue by techwes** [react-native-community/react-native-maps#1995] opened 2018-01-26 20:19 UTC
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

react-native: 0.52.2
react: 16.2.0
react-native-maps: 0.19.0

Works on iOS target platform 9.0 (Apple Maps, have not tried Google Maps)
Does **not** work on Android, tried multiple versions including 6.0 emulator and a 8.1.0 Pixel 2

### Steps to Reproduce

1. `react-native init <projectName>`
2. Install RN Maps according to the instructions
3. Test a non controlled map (aka uses `initialRegion` instead of `region`) to confirm everything is installed correctly. It will work. (see master branch of repo referenced in reproducible demo section)
4. Change the map into a controlled map (using `region` and `onRegionChange`)
5. Run on an Android device or emulator. You will see that when you try to move the map around the whole map jitters and makes it impossible to move around
6. (optional) Test the same code on iOS (Apple Maps) it will work fine

### Expected Behavior

I would have expected to be able to move the map around like normal on Android. This example is taken straight out of the Readme and has worked for me perfectly on another project that is running on older RN and RN Maps (RN 0.48.4, RN Maps: 0.16.4).

### Actual Behavior

Whenever you try to move the map the whole map jitters and doesn't move at all. Sometimes you can get very small movements to work but it is not usable. It almost seems as if the updates to the state are not happening in sync with the dragging of your finger making it just bounce back and forth.

This is only an issue on Android not iOS.

### Reproducible Demo

https://github.com/techwes/rn-maps-playground/tree/issue-map-move

The repo above I just created to play around with RN Maps and confirm this issue was not due to some of my other code. The branch linked above has the code that reproduces the issue. The master branch is actually a version that works (just to prove I didn't mess up the installation).

You will notice that this code is the same as "Using a MapView while controlling the region as state" section of the readme, but it doesn't work on Android

**Comment by markmssd** [comment] 2018-01-26 21:13
That's weird, i'm actually controlling the map's position/zoom via redux state, which works in both iOS/Android.

**Comment by markmssd** [comment] 2018-01-26 21:17
I think i understand why... whenever you move, you trigger the onRegionChange, which then sets the position back to what it was... which is expected behaviour. If you use `onRegionChangeComplete` instead, you should be able to keep moving. Then, only when you release, you might see a little "jitter".

Unless I completely misunderstood your issue :p

**Comment by alvelig** [comment] 2018-01-26 21:41
@techwes First of all thank you very much for posting a well worked issue. If it worked on 0.16.4 could you please find the commit or at least version where it stopped.

P.S. I personally never managed to get it working well controlling region (neither in state nor in redux), I just store the region in onRegionChange, but control it with `animateTo`. (It's kinda workaround to your problem).

**Comment by rafetkhallaf** [comment] 2018-01-27 10:20
Confirmed on iOS as well. At the time being I moved from onRegionChange to onRegionChangeComplete, it has that little lag but at least the users can still use the map.

the issue is when calling setState in onRegionChange it's like it's waiting for setState to complete.

**Comment by techwes** [comment] 2018-01-28 18:53
@rafetkhallaf so if doesn't work for you on iOS either? That is strange because it worked fine for me on iOS. Is the "waiting for setState to complete" piece a guess or something based on the code? Since setState is async it seems like it would be hard for it to be accidentally waiting on it. It seems to me like the setState is happening out of sync with the different onRegionChange so it is getting set back to a previous region value causing the jitter.

@markmssd I will try onRegionChangeComplete and see if that works. But, just to be clear I am not setting the position "back to what it was" I am setting it to the new position given by the onRegionChange event. Like I said this has always worked fine for me in the past but has stopped working with the current RN + RN Maps

@alvelig Interesting that it has never worked for you, that does sound like a possible work around and I might end up going with something similar in the short term. However in the long term controlling the region via state should either be fixed or dropped from the docs. I thought about doing a `git bisect` like you are suggesting but I was unsure how to set up my project so I could run the example on each different commit in this repo. Especially with the changes in installation steps from then to now.

I did just realize I am using the newest version of RN when it looks like the package.json has the version before (0.51.0). Any idea if that has something to do with it? (have not had the time to try with that version of RN yet)

**Comment by alvelig** [comment] 2018-01-28 20:54
@techwes when you are done with initial installation, especially on Android, you just:
```
yarn remove react-native-maps
yarn add https://github.com/react-community/react-native-maps.git#0.16.4
```
instead of 0.16.4 (tag) can go commit or branch.

**Comment by rafetkhallaf** [comment] 2018-01-28 21:17
@techwes Yes, I believe so. because when I remove the setState line, everything works as expected. and I understand setState is async and that what was troubling me. i thought to set the onRegionChange function be an async, but nothing happened, so when i removed the setState everything worked fine.

`..

  onRegionChange(region) {
    this.setState({ region: region});
  }

  render() {

    return (
      <StickFrame
        statusBar={true}
        statusBarLight={this.state.nightTime}
        screenBackgroundColor={'#f1f1f1'}
      >
        {this.state.region ?
          <View style={{flex: 1}}>
            <MapView.Animated
              style={componentStyle.mapView}					
              region={this.state.region}
              onRegionChangeComplete={this.onRegionChange.bind(this)}
              provider={PROVIDER_GOOGLE}
..`

@alvelig Why are you using 0.16.4? only asking because my code is using react-native-maps "0.17.1" and my problem started with this update.

**Comment by rafetkhallaf** [comment] 2018-02-07 08:36
Any updates on this issue?

**Comment by rborn** [comment] 2018-02-07 12:22
@rafetkhallaf don't make region depending on state

**Comment by techwes** [comment] 2018-02-12 20:09
I got pulled onto more pressing things so left this hanging for now. My plan when I get back to this is to remove the need to control the region through the state and use `animateTo` when I need to change the region, as @alvelig suggested. 

If it is a bad practice to control region with state, then I propose we remove references to it in the Readme and call it out as a bad practice. Almost every code snippet example in the Readme references:
```js
<MapView
  region={this.state.region}
  onRegionChange={this.onRegionChange}
>
```
which implies that controlling the region as state is a best practice. Luckily it looks like the actual examples in the examples folder generally use `initialRegion` (at least the view I clicked through).

I would be happy to make this documentation update, I just want to make sure the powers at be agree this is a good idea so I don't waste my time

**Comment by alvelig** [comment] 2018-02-12 20:17
@techwes I see your point, but there's a problem, that it's not a totally bad practice, but actually just a use case. You may intentionally use state to control region, but you should be aware of the consequences. I agree that this cases should be cleared in the docs.

**Comment by techwes** [comment] 2018-02-12 20:33
Yeah I don't think I know exactly what the consequences are, so maybe I am not the best to do this? Or maybe if you give me a use case where it is a good idea to control region via state  (and that actually works) that would help. I just know the example in the docs does not work  and it doesn't seem like this is best recommendation for most use cases

**Comment by alvelig** [comment] 2018-02-12 20:35
One possible use case is when you want to restrict area shown. But actually you are correct. Most of them are doable with `animateTo`

**Comment by rafetkhallaf** [comment] 2018-02-12 20:53
I know this is outside your convo right now, but it got little confusing for me now. just to confirm, the problem is not with onRigonChange => setState({ region: region}), it's with region={this.state.region}. is this correct?

**Comment by techwes** [comment] 2018-02-12 22:59
I think yes, but I would not have phrased it that way. It is more an issue of them being used together than with either individually. To be clear, there is no issue with onRegionChange being called, and you could certainly set the state in that function and it would work fine. But once you hook that region state up to the region prop is when this bug occurs.

**Comment by alvelig** [comment] 2018-02-13 00:20
Exactly, the issue is expecting the map to pan fluently while controlling it's region with setState(), as map render() might take more time than you expect to change the region.

**Comment by rafetkhallaf** [comment] 2018-02-16 17:47
@techwes @alvelig I tried everything to get the map to work as smooth as before but no luck. how are you guys setting the region when somebody moves the map around? this.setState({}) is not working as we discussed and almost every tutorial i found is doing the same thing.

** we are also using expo and it's using 0.19 and i noticed today that there is a new version here that solved some of the other problems i was having with RNM but don't know how to upgrade it one expo, not sure if that is even possible, but i searched around and i posted the questions hoping that it is possible without waiting for the next sdk update. So if this issue is fixed on RNM 0.20.1 just confirm it for me and I'll focus on following up with expo.

@rborn sorry i missed your comment. I'm not trying to set the region using the state, i'm trying to get the region when the user moves the map around.

**Comment by rafetkhallaf** [comment] 2018-03-11 08:32
I guess then it's an expo issue and not reactnative-maps @ethantran. I just came back to this issue i'm going to do some more testing on it and see if we can solve this.

**Comment by techwes** [comment] 2018-03-11 16:32
@rafetkhallaf I have been able to sidestep this issue in both a pure naive and an expo (SDK 25) app using  I have been able to side step this issue using the suggestion from @alvelig which is to not use the region prop (only use initialRegion aka don't control the region with state), keeping track of the region in the state via onRegionChanged, and using `animateTo` to change the region when needed. Have you tried this method? I think it actually should be the preferred way to go.

So I would like to get back to the matter of either fixing this issue, or making the documentation clear this is not an issue. It seems from earlier conversation that controlling region with state does have its use cases but generally is not a best practice (because it causes this issue). If that is indeed the case, then we can close this issue by making the documentation clear. Otherwise, we should actually fix it so controlling the region as state works as it used to. The documentation updating is something I would be happy to do. Fixing the library however is outside of the current time I have to commit (since I have yet to contribute or even browse the inner workings of this library and have very little time to do so)

**Comment by alvelig** [comment] 2018-03-11 17:58
I'd go for documenting that `animateTo` is generally preferable before controlling `region` in state due to the nature of ReactNative `render` method. I'm even against initialRegion, but don't know yet how to handle some border cases.

Something like: 
**NOTE:** the approach used in examples where `region={this.state.region}` is only for demonstration purposes and extremely discouraged to apply due to unresolved performance issues. If you need to change region programmatically, use animation [methods](https://github.com/react-community/react-native-maps/blob/master/docs/mapview.md#methods)

**Comment by rafetkhallaf** [comment] 2018-03-11 18:04
@techwes @alvelig I agree with the documentation seince this is the best practice/approach.

**Comment by davidhellsing** [comment] 2018-08-27 09:44
The only problem with using f.ex `animateToRegion` is that it’s not possible to move the map without duration in android (it seems to use at least 400ms even if I set it to zero)

**Comment by Lavkushwaha** [comment] 2018-09-17 10:18
`<MapView
          style={styles.map}
          region={this.state.mapRegion}
          showsUserLocation={true}
          followUserLocation={true}
          onRegionChange={() => this.onRegionChange()}>
          <MapView.Marker
            coordinate={{
              latitude: (this.state.lastLat ) || -36.82339,
              longitude: (this.state.lastLong ) || -73.03569,
            }}
            title="Hello"
            description="Hello d"
            onPress={() => alert("hello re")}
            >
            <View>
              <Text style={{color: '#000'}}>
                { this.state.lastLong } / { this.state.lastLat }
              </Text>
            </View>
          </MapView.Marker>
        </MapView>
`

i tried using fat arrow function and it worked.

` onRegionChange={() => this.onRegionChange()}>`

problem was with whenever region changes it call backs immidiately, because of it when i try to drag my map pointer it shakes and then i use this call back function and it works perfect.

**Comment by aryalprakash** [comment] 2018-11-12 06:20
Removing `region = {this.state.region}` from `MapView` solved this for me.

**Comment by wmoore98** [comment] 2019-01-02 02:13
Following Lavkushwaha's suggestion, I simply changed my code from the example in the docs to a fat arrow function and **amazingly** the jittery behavior went away. Any thoughts why it would make a difference?

                    // onRegionChange={this.onRegionChange}
                    onRegionChange={() => this.onRegionChange()}

**Comment by MatheusGit** [comment] 2019-02-23 13:10
`onRegionChange={(region) => props.map.animateToRegion(region,0)  }` work for me :)

**Comment by cicer1** [comment] 2019-03-06 16:30
as @markmssd noticed there will be a little "jitter" at the end of your movement on the map especially if you give a big scroll and leave the map go. It is more evident on real device in my case. 
In this case debounce will help

```
          <MapView
            provider={Platform.OS === 'ios' ? null : PROVIDER_GOOGLE}
            initialRegion={region}
            onRegionChangeComplete={debounce(this.onRegionChange, 1000, {
              leading: false,
              trailing: true
            })}
            zoomControlEnabled
          />
```

**Comment by salah-ghanim** [comment] 2019-03-06 20:02
I'm closing this issue because it seems like incorrect usage instead of an actual bug. stackoverflow seems like a better place for such discussion.

**Closed by salah-ghanim** 2019-03-06 20:02 UTC
Labels: Android

**Comment by stigi** [comment] 2019-04-17 13:53
I believe that this is still a problem on Android. At least the [example from the Readme](https://github.com/react-native-community/react-native-maps#using-a-mapview-while-controlling-the-region-as-state) is broken.

I noticed that iOS is implementing a feature that prevents onRegion callbacks to fire when programmatically updating the region (`[AirMap ignoreRegionChanges]`) while Android seems to be missing that part completely.

**Comment by jakoblorz** [comment] 2019-05-19 18:06
Had the same problem because the [Readme](https://github.com/react-native-community/react-native-maps/blob/master/README.md#using-a-mapview-while-controlling-the-region-as-state) pointed me to the onRegionChange when having the region as state.

**Comment by LuizFBrisighello** [comment] 2019-10-21 14:52
@jakoblorz @stigi  Did you guys solved this in any way?

I'm cracking my head for almost a week now.. I need to store the latitudeDelta on a state to calc the users current zoom and display the markers based on that, and update it on the go with `useEffect` by passing the zoomValue as a second argument.

Can someone help me?

**Comment by gandarain** [comment] 2019-12-01 03:39
I using this guide, maybe you should try
https://alizahid.dev/blog/keep-marker-in-center-and-move-map-around-it

**Comment by daxilshah** [comment] 2020-04-16 22:21
I was struggling to find the solution to this problem since couple of weeks, and suddenly i thought of a fix to this issue in this way.

First thing, If you need a state based region, don't go for state based region. 
Why?
Because, in order to update the region, you will require 
`onRegionChange={this.onRegionChange}`
which makes map sluggish and does not let the map move smoothly since you're updating state every time user navigates/pans, which re-renders your entire component. Definitely a heavy operation.
Please note here that changing above line to 
`onRegionChange={() => this.onRegionChange}`
does not make any sense, since you're not capturing region from the callback and hence, onRegionChange will never be able to update the state. But still, your map will work smooth because you're not at all updating state. If at any point you'll try to console your region, you'll get initialRegion only which you had set programatically and not the region where user currently is looking at.

Also, some developers have mentioned to use onRegionChangeComplete method instead of onRegionChange, but it did't work me actually. onRegionChangeComplete keeps moving my map automatically without user interactions. 

So, what my suggestion is, instead keeping region in state of the component, you can keep region as class variable using `this.region = <your initial state>`

modify your onRegionChange method to, 
`onRegionChange = (region) => {
        this.region = region;
    }`

this will not change the state every time user navigates/pans in the map. 
PS: At any point if you need to re-assign the region and you need map to load latest region, you can always have a workaround like below.

Have one state variable which would be of dateTime, and whenever you need to re-render your component with latest region, just update the dateTime state variable.

Hope this helps!
