### ISSUE TITLE
can't pinch to zoom when touching marker

### ISSUE THREAD

**Issue by stereodenis** [react-native-community/react-native-maps#522] opened 2016-09-01 11:15 UTC
When I want to zoom map and initial touches are on markers — it's not zooming

**Comment by sjmueller** [comment] 2016-09-03 09:15
Same problem here.

**Comment by alexHlebnikov** [comment] 2016-09-05 04:51
You can try animate zoom this way:
```
this.refs.map._component.animateToRegion(animatedRegion, 600);
```

**Comment by stereodenis** [comment] 2016-09-05 08:30
@alexHlebnikov I want to use pinch to zoom

**Comment by leandroalonso** [comment] 2016-09-18 16:58
Any help or update about this issue?

**Comment by sjmueller** [comment] 2016-09-28 05:02
This is a serious problem with the basic usability of the component. I'm willing to take a stab at a fix, but need a bit of guidance. @naoufal @spikebrehm @gilbox care to chime in?

**Comment by sjmueller** [comment] 2016-09-28 05:48
So after a bit of debugging, the problem lies here: https://github.com/airbnb/react-native-maps/blob/master/ios/AirMaps/AIRMap.m#L144

A crude change that fixes zoom when initial touch is over markers:

```
- (BOOL)gestureRecognizer:(UIGestureRecognizer *)gestureRecognizer shouldReceiveTouch:(UITouch *)touch {
    return YES;
}
```

Obviously letting the map swallow every gesture will remove the ability to interact with markers, so we have to dig in and detect zoom (and other intents) so that we know when to let the `MKMapView` handle it properly. Will keep working on it, but please feel free to add comments/opinions.

**Comment by sjmueller** [comment] 2016-09-28 07:10
After more analysis, my post above is somewhat misleading. I think the problem is more related to the hitTest here: https://github.com/airbnb/react-native-maps/blob/master/ios/AirMaps/AIRMap.m#L153-L159.

When images are used in Markers and a gesture starts on top of one, `[super hitTest:point withEvent:event]` will return that Image as the hitTest view instead of the `MKNewAnnotationContainerView` that is capable of responding properly to the pinch or zoom.

My knowledge is limited for best practices in all the various gesture event handling combinations on iOS, but I think it's probably safe to detect the type of gesture and just short circuit the hitTest view to be `MKNewAnnotationContainerView` for these cases. But we'd also have to think about other gestures too. For instance, when you double tap on a marker in iOS Maps app, it will zoom in accordingly, whereas single tap will bring up the marker detail overlay.

**Comment by carleryd** [comment] 2016-11-15 18:28
#544

**Comment by carleryd** [comment] 2016-11-15 18:32
My ticket #544 was a duplicate of this.
I don't know how to solve this problem, but when testing I find that I can pinch zoom over simple annotations, and custom image annotations(either with nested Image/View or marker image prop) on the initial render, but if more markers are rendered on the screen the previously rendered markers can no longer be pinch-zoomed over.

**Comment by carleryd** [comment] 2016-11-16 00:15
I managed to get sjmuellers PR to work when using onSelect instead of onPress. Check out my comment on #623

**Comment by jamesone** [comment] 2017-01-21 03:24
Any update on this? Is there a way around this? Can we add a prop to the markers or something to allow the pinch and zoom? 

The map should detect when two fingers are on the screen & disable clicks on the markers?

**Comment by tirnovali** [comment] 2017-01-31 13:59
any update on this issue pls?

**Comment by dot3bumpmap** [comment] 2017-02-22 17:52
Run into this issue too. https://github.com/airbnb/react-native-maps/pull/623 helps but is a tradeoff. Was anyone able to fix this  completely?

**Comment by lylynguyen** [comment] 2017-04-07 17:39
I have the same issue with the marker. Does anyone have a solution?

**Comment by creeperyang** [comment] 2017-04-28 09:17
The bug exists for a long time, so any official plan to fix the bug?

**Comment by jamesone** [comment] 2017-06-29 06:02
I'm guessing there is no official fix yet? Is there a work around for this? Has anyone used the workaround from: @grundmanise (as referenced above)

**Comment by pablito25sp** [comment] 2017-07-12 15:37
Same as @carleryd, I can confirm @sjmueller PR works moving callback from onPress to onSelect.
Thank you.

**Comment by alvelig** [comment] 2017-12-15 05:36
That happens...

**Comment by christopherdro** [comment] 2019-01-17 09:23
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/react-native-community/react-native-maps/releases).

Thank you!

**Closed by christopherdro** 2019-01-17 09:23 UTC
Labels: bug, help wanted

**Comment by sami-juvonen** [comment] 2024-02-09 21:06
I'm currently having this issue and #623 doesn't seem to work anymore. Is there a way to stop markers grabbing gestures?
