### ISSUE TITLE
Blank map on android device

### ISSUE THREAD

**Issue by mjabdelilah** [react-native-community/react-native-maps#2766] opened 2019-03-26 17:10 UTC
React native is blank on my android device. It's just a grey screen with the google logo.
i tried so many solutions: { enable API key, change the style, etc... }

**### app\build.gradle**

`apply plugin: "com.android.application"

import com.android.build.OutputFile

project.ext.react = [
    entryFile: "index.js"
]

apply from: "../../node_modules/react-native/react.gradle"

def enableSeparateBuildPerCPUArchitecture = false

def enableProguardInReleaseBuilds = false

android {
    compileSdkVersion rootProject.ext.compileSdkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        applicationId "com.maptest"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0"
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86", "arm64-v8a", "x86_64"
        }
    }
    buildTypes {
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            def versionCodes = ["armeabi-v7a":1, "x86":2, "arm64-v8a": 3, "x86_64": 4]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
}

dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"
    implementation "com.facebook.react:react-native:+"  // From node_modules
    implementation project(':react-native-maps')
    implementation 'com.android.support:support-v4:28.0.0'
}

task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}
`

**### android\build.gradle**
`
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.3.1'
        

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        google()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
    }
}

`

**### package.json**

`
{
  "name": "mapTest",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "react": "16.8.3",
    "react-native": "0.59.2",
    "react-native-maps": "^0.20.1"
  },
  "devDependencies": {
    "@babel/core": "7.4.0",
    "@babel/runtime": "7.4.2",
    "@react-native-community/eslint-config": "0.0.3",
    "babel-jest": "24.5.0",
    "eslint": "5.15.3",
    "jest": "24.5.0",
    "metro-react-native-babel-preset": "0.53.1",
    "react-test-renderer": "16.8.3"
  },
  "jest": {
    "preset": "react-native"
  }
}

`

**### App.js**

`
import React, { Component } from 'react';
import { StyleSheet, View, Dimensions } from 'react-native';
import MapView from 'react-native-maps';

var { width, height } = Dimensions.get('window')
export default class App extends Component {
  render() {
    return (
      <MapView
        style={styles.map}
        initialRegion={{
          latitude: 37.78825,
          longitude: -122.4324,
          latitudeDelta: 0.0922,
          longitudeDelta: 0.0421,
        }}
      />
    );
  }
}

const styles = StyleSheet.create({
  map: {
    flex: 1,
    width: width,
    height: height,
  },
});

`

as a result i have this screenshot 

![RN Issue](https://user-images.githubusercontent.com/44535652/55018082-010bc180-4fea-11e9-8888-48853c25962a.jpg)

**Comment by rborn** [comment] 2019-03-26 17:37
When you see the logo but a blank map it's 99% an api key issue. 
Check the logcat messages.

**Comment by mjabdelilah** [comment] 2019-03-26 20:17
> logcat messages

Ifollow the instructions on the documentation, I think that there is nothing wrong with API Key,

![001](https://user-images.githubusercontent.com/44535652/55030361-2279a700-5004-11e9-9959-0e8cd3d56cab.PNG)

**Comment by rborn** [comment] 2019-03-27 08:41
@mjabdelilah  you need to get the logs from the device to see what's going on there. http://adbshell.com/commands/adb-logcat

**Comment by mjabdelilah** [comment] 2019-03-27 14:17
@rborn when i use this command `adb logcat`, Many non-stop information appears on the screen.
I wanted to share it with you but she does not stop.

here is شn example of what I get:
![001](https://user-images.githubusercontent.com/44535652/55083179-fd844300-509a-11e9-91ab-4ab50325627f.PNG)

**Comment by rborn** [comment] 2019-03-27 16:29
try `adb logcat | grep "Google Maps Android API"`

**Comment by mjabdelilah** [comment] 2019-03-27 19:58
@rborn this what i got 
![001](https://user-images.githubusercontent.com/44535652/55107983-7a7ae100-50ca-11e9-9242-fae446111a90.PNG)

sorry for bothering you again

**Comment by rborn** [comment] 2019-03-27 20:11
@mjabdelilah  go to your google api console, and try to set the key as "none" on the restricted section. Once it works, you can play then to restrict  it for android/ios

**Comment by mjabdelilah** [comment] 2019-03-27 20:54
@rborn when i set the key as "none", my app crashes. and when i restrict it for android i got the first problem (blank map).

**Comment by rborn** [comment] 2019-03-27 21:27
And why is it crashing? What are the logs saying?

**Comment by mjabdelilah** [comment] 2019-03-28 13:01
@rborn if i just change anything about the first API Key, my app craches.
i tried to create a new API key but i got the same result.
![001](https://user-images.githubusercontent.com/44535652/55159676-86fa4a80-5159-11e9-83f3-3036d808e125.PNG)

**Comment by Dwlad90** [comment] 2019-03-28 20:28
[https://github.com/react-native-community/react-native-maps/issues/951#issuecomment-272286167](https://github.com/react-native-community/react-native-maps/issues/951#issuecomment-272286167)
This helped me

**Comment by mjabdelilah** [comment] 2019-03-28 20:41
@Dwlad90 thanks bro but still the same problem, a blank screen.

**Comment by ImFranQ** [comment] 2019-04-19 06:15
i had the same issue, this work for me:

- Enable Google maps service in the google console.

Go to console -> menu -> api and services -> panel -> click "Enable api and services" -> search google maps -> select it -> enable -> run app -> congratulations..

PD: sorry for my english I'm latino

**Comment by rborn** [comment] 2019-04-23 09:38
Closing as per https://github.com/react-native-community/react-native-maps/issues/2766#issuecomment-484778579

**Closed by rborn** 2019-04-23 09:38 UTC

**Comment by conor909** [comment] 2020-04-12 13:16
@ImFranQ which google maps service to you select?  I have:

- Maps SDK for iOS
- Maps SDK for Android
- Maps Embed API
- Maps Javascript API

My iOS & Android SDKs arnt working

**Comment by thuantvDr4** [comment] 2020-06-16 09:55
this issue, i have fixed:
because, the first time I install by yarn add,
so, I remove it (yarn remove react-native-maps)
and after that, i install by npm (npm install react-native-maps --save-exact)
and last, i finished!

![image](https://user-images.githubusercontent.com/24288310/84760387-23746b00-aff2-11ea-9196-3589f5b7c1b8.png)

**Comment by mehderilker** [comment] 2020-07-06 09:36
If you get this error after adding the necessary dependency like in the document.
The cause of the error, an api-induced problem (%99).
If there is a "restriction" in the api key you created(https://console.cloud.google.com), you may have entered the code SHA1 or package name incorrectly.

Good luck with.

**Comment by citizen-dror** [comment] 2020-08-17 11:26
one more option to key problem 

is if you forget / misunderstood section 3.1 [in the installtion ](https://github.com/react-native-community/react-native-maps/blob/master/docs/installation.md) !!! 
 
replace :
```
 supportLibVersion   = "xxx"
 playServicesVersion = "17.0.0" // or find latest version
 androidMapsUtilsVersion = "xxx"
```

with somthing like:

 ```
supportLibVersion = "28.0.0"
 playServicesVersion = "17.0.0"  
 androidMapsUtilsVersion = "2.0.3"
```

i did'nt uderstand what to replace supportLibVersion  , androidMapsUtilsVersion  version, skipped it and got gray screen for hours !! without a clear bug!  

see[ this qusetion ](https://stackoverflow.com/questions/58806151/get-supportlibversion-playservicesversion-and-androidmapsutilsversion-va) to find   latest version

**Comment by sgup** [comment] 2020-11-26 23:06
I was able to fix it by removing the API restriction on the key (It still restricts to my app):

![image](https://user-images.githubusercontent.com/404386/100396152-02d52600-3012-11eb-863e-91f2b5db094b.png)

**Comment by jcodinan** [comment] 2021-07-28 18:44
Hi! I have the same problem with my app, a gray background with the Google logo on It. the most strange thing is that I create another app from scratch with `react-native init`, with the same ApiKey and it works. I have the same configuration for both apps. Can you guys help me with this? it's posible this problem is associated with another package installed in my first app or something?

**Comment by mateoguzmana** [comment] 2022-05-15 10:41
> i had the same issue, this work for me:
> 
> * Enable Google maps service in the google console.
> 
> Go to console -> menu -> api and services -> panel -> click "Enable api and services" -> search google maps -> select it -> enable -> run app -> congratulations..
> 
> PD: sorry for my english I'm latino

If you see the Google logo, this one does the trick. It simply doesn't show anything because you haven't allowed Google to display the map for Android.

Don't forget to clean the build and run it again afterwards.

**Comment by sunny-mittal** [comment] 2022-08-10 03:19
> i had the same issue, this work for me:
> 
> * Enable Google maps service in the google console.
> 
> Go to console -> menu -> api and services -> panel -> click "Enable api and services" -> search google maps -> select it -> enable -> run app -> congratulations..
> 
> PD: sorry for my english I'm latino

I don't know why someone downvoted this. Was definitely my issue and others'. Many thanks :)

**Comment by ChrisCoder9000** [comment] 2022-12-12 10:47
> this issue, i have fixed: because, the first time I install by yarn add, so, I remove it (yarn remove react-native-maps) and after that, i install by npm (npm install react-native-maps --save-exact) and last, i finished!
> 
> ![image](https://user-images.githubusercontent.com/24288310/84760387-23746b00-aff2-11ea-9196-3589f5b7c1b8.png)

I would like to know why after installing react-native-maps with npm works and with yarn it doesn't 🤔

**Comment by malikhamza0546** [comment] 2023-03-28 17:30
> @ImFranQ which google maps service to you select? I have:
> 
> * Maps SDK for iOS
> * Maps SDK for Android
> * Maps Embed API
> * Maps Javascript API
> 
> My iOS & Android SDKs arnt working

This works for me enable all these services after generating API key

**Comment by excelso** [comment] 2024-01-06 03:20
Instead of android:name="com.google.android.geo.API_KEY" try using android:name="com.google.android.maps.v2.API_KEY"

**Comment by filiperochalopes** [comment] 2024-05-14 08:06
> * Maps Javascript API

For me just activate *Maps Javascript API* and worked fine

**Comment by filiperochalopes** [comment] 2024-05-14 08:06
> @ImFranQ which google maps service to you select? I have:
> 
> * Maps SDK for iOS
> * Maps SDK for Android
> * Maps Embed API
> * Maps Javascript API
> 
> My iOS & Android SDKs arnt working

For me just activate **Maps Javascript API** and worked fine
