### ISSUE TITLE
CalloutSubview was not found in the UIManager on Android

### ISSUE THREAD

**Issue by romulofgouvea** [react-native-community/react-native-maps#3378] opened 2020-04-07 17:12 UTC
# Bug

![bug](https://user-images.githubusercontent.com/16581559/78698153-3f63de00-78d8-11ea-8696-014a75f70c09.png)

## Environment info

`react-native info` output:

System:
    OS: Windows 10 10.0.18362
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 2.76 GB / 15.87 GB
  Binaries:
    Node: 12.14.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.21.1 - C:\Program Files\nodejs\yarn.CMD
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    Android Studio: Version  3.5.0.0 AI-191.8026.42.35.6010548
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5

Library version: 0.27.1

## Steps To Reproduce

1.Create component function
2. create MapView with one marker
3. add Callout and CalloutSubview

## Reproducible sample code

            <MapView
                ref={mapView}
                onRegionChangeComplete={onRegionChange}
                showsUserLocation
                rotateEnabled={false}
                style={styles.map}
                minZoomLevel={15}
            >
                    <MapView.Marker
                        coordinate={{ latitude: marker.latitude, longitude: marker.longitude }}
                    >
                        <Callout
                            alphaHitTest
                            tooltip
                            onPress={e => {
                                if (
                                    e.nativeEvent.action === 'marker-inside-overlay-press' ||
                                    e.nativeEvent.action === 'callout-inside-press'
                                ) {
                                    return;
                                }

                                Alert.alert('callout pressed');
                            }}
                        >
                            <CustomCallout> //Copy by example
                                <Text>{`This is a custom callout bubble view`}</Text>
                                <CalloutSubview>
                                    <Text>Click me</Text>
                                </CalloutSubview>
                            </CustomCallout>
                        </Callout>
                    </MapView.Marker>
            </MapView>

**Comment by rborn** [comment] 2020-04-08 09:40
Closing, Not a bug, not supported by android https://github.com/react-native-community/react-native-maps/blob/master/docs/callout.md#calloutsubview--component-api
Please read well the docs 😉

**Closed by rborn** 2020-04-08 09:40 UTC
