### ISSUE TITLE
onRegionChange returns negative LongitudeDelta on Android.

### ISSUE THREAD

**Issue by heikkihautala** [react-native-community/react-native-maps#1386] opened 2017-06-05 12:44 UTC
version: **0.15.2**

If I zoom out the map and pan the map around the globe, `onRegionChange` may return a region with negative `longitudeDelta`. On iOS using Google maps provider, `longitudeDelta` is always positive.

Here's a demonstration:
https://www.dropbox.com/s/j5b6vevvlq22yie/longitudeDelta.gif

[Edit]
Looks like the value is always `correctValue - 360` when negative. So I can work around it by adding the 360 degrees when ever I get a negative value.

**Comment by FZSS** [comment] 2017-08-12 07:37
Did you know what causes this error?
I found a similar bug where onRegionChange return a region with a longitude >180, when dragging around the 180 longitude line.

**Comment by IjzerenHein** [comment] 2017-10-17 21:52
This is most likely caused by these lines in `RegionChangeEvent.java`:

```java
region.putDouble("latitudeDelta", bounds.northeast.latitude - bounds.southwest.latitude);
region.putDouble("longitudeDelta", bounds.northeast.longitude - bounds.southwest.longitude);
```

**Comment by DanGDroid** [comment] 2018-02-13 12:38
i can see a fix for this in
`react-native-maps/lib/ios/AirGoogleMaps/AIRGoogleMap.m`
`makeGMSCameraPositionFromMap `

```javascript
if(bounds.northEast.longitude >= bounds.southWest.longitude) {
    //Standard case
    center = CLLocationCoordinate2DMake((bounds.southWest.latitude + bounds.northEast.latitude) / 2,
                                        (bounds.southWest.longitude + bounds.northEast.longitude) / 2);
    longitudeDelta = bounds.northEast.longitude - bounds.southWest.longitude;
  } else {
    //Region spans the international dateline
    center = CLLocationCoordinate2DMake((bounds.southWest.latitude + bounds.northEast.latitude) / 2,
                                        (bounds.southWest.longitude + bounds.northEast.longitude + 360) / 2);
    longitudeDelta = bounds.northEast.longitude + 360 - bounds.southWest.longitude;
  }
```

can we please have the same fix for Android?? @christopherdro @IjzerenHein

**Closed** 2020-03-04 21:42 UTC

**Comment by Nargle30** [comment] 2020-07-28 10:20
Have the same issue with react-native-maps 0.27.1
react-native 0.61.0

**Comment by fl-sachika** [comment] 2023-09-13 06:02
Have the same issue with react-native-maps 1.7.1
react-native 0.66.5
