### ISSUE TITLE
Impossible use pointForCoordinate. Got Unhandled promise rejection on Android

### ISSUE THREAD

**Issue by cklinx** [react-native-community/react-native-maps#2578] opened 2018-11-10 14:31 UTC
Hi,
when i try to use 
```
let LatLng = {
        latitude: this.state.region.latitude,
        longitude: this.state.region.longitude,
      } 
this.map.pointForCoordinate(LatLng)
``` 
i get this error: `[Unhandled promise rejection: TypeError: undefined is not an object (evaluating '_reactNative.NativeModules.AirMapModule.pointForCoordinate')]`.

Same thing with `coordinateForPoint`.

I use last Expo release and testing it on Android.

Thanks in advance.

### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

    "expo": "^31.0.4",
    "react": "16.5.0",
    "react-native": "0.57",
    "react-native-maps: "0.22.0"

  Target Platform: Android 8, Android Emulator

### Steps to Reproduce

```
let LatLng = {
        latitude: this.state.region.latitude,
        longitude: this.state.region.longitude,
      } 
this.map.pointForCoordinate(LatLng)
``` 

### Expected Behavior
Get the correct point.

### Actual Behavior

error: `[Unhandled promise rejection: TypeError: undefined is not an object (evaluating '_reactNative.NativeModules.AirMapModule.pointForCoordinate')]`.

**Comment by rborn** [comment] 2018-11-10 14:34
Please update your issue with the template or I'll close it

**Comment by cklinx** [comment] 2018-11-10 14:53
> Please update your issue with the template or I'll close it

Did it

**Comment by hennzen** [comment] 2018-11-15 07:42
Got same issue. Using Expo SDK v29.0.0 though
`"react-native": "https://github.com/expo/react-native/archive/sdk-29.0.0.tar.gz",`
which integrates react-native-maps v0.21.0

**Comment by cjol** [comment] 2019-02-19 18:08
I hate to +1 without any new information, but I've been running against this too. I think Expo isn't linking correctly, because `NativeModules.AirMapModule` is undefined for this function, and also for `getCamera`, `takeSnapshot`, `getMapBoundaries`, `coordinateForPoint`.

I don't even know where to start when it comes to linking modules, but using Expo means I can't do anything about it anyway. Would love a steer if anyone has any ideas.

**Comment by gauthampait** [comment] 2019-03-24 12:26
Any updates on this ? Checked with v0.23.0. Getting the same error on Android.

**Comment by rborn** [comment] 2019-03-25 08:55
@gauthampait please try with the latest master version and let us know.

**Comment by cjol** [comment] 2019-04-03 10:56
I can reproduce with the latest master:
```
[Unhandled promise rejection: TypeError: undefined is not an object (evaluating '_reactNative.NativeModules.AirMapModule.pointForCoordinate')]
- node_modules/react-native-maps/lib/components/MapView.js:779:40 in pointForCoordinate
```

**Comment by natan04** [comment] 2019-06-25 20:51
Got the same issue. 
the NativeModules.AirMapModule is undefined. (SDK 33.0.0)

**Comment by ajdinahmetovic** [comment] 2019-07-03 10:03
Any update?  I have the same issue. I am using react native with expo. I get TypeError that undefined is not an object evaluating _reactNative.NativeModules.AirMapModule.coordinateForPoint.

**Comment by ajdinahmetovic** [comment] 2019-07-03 15:41
I found a workaround for this problem! 
Maybe it will help someone who has similar usecase.
I needed to drag Animated View o map and detect where that view is dropped. Because map has **onPress** event that returns coordinates where user tapped on screen. We can use that to retrive LatLng. I returned XY points of where Animated View is dropped and then simulated user tap on map programatically and returned LatLng from **onPress** event.

**Comment by AlessandroAnnini** [comment] 2019-09-03 12:47
Any news?

**Comment by richtiko** [comment] 2019-12-22 23:35
Any updates?

**Comment by sardok** [comment] 2020-01-16 12:19
Same. Expo sdk 34.0.0.

**Closed** 2020-03-04 21:55 UTC
Labels: Expo
