### ISSUE TITLE
strange issue with map on andriod

### ISSUE THREAD

**Issue by wonskarol** [react-native-community/react-native-maps#1399] opened 2017-06-10 10:47 UTC
Hey, a wrote a app that uses react-native-maps and it works perfectly on iOS.
I wanted to run it on Android, did steps from installation guide (https://github.com/airbnb/react-native-maps/blob/master/docs/installation.md#android).
When I open my app, I get blank page with markers (can't scroll, zoom, press on markers etc.)
![screenshot_1497088047](https://user-images.githubusercontent.com/5656856/27002065-2b99d5c4-4dd8-11e7-9542-4c59762d4826.png)
But, when I hide the app and then make it active again, tiles are loaded (sometimes with names of the places and sometimes not 🤔)
![screenshot_1497088055](https://user-images.githubusercontent.com/5656856/27002089-621ff7b8-4dd8-11e7-9ab3-505b118b2450.png)
Unfortunately I still can't interact with map.
I suppose the API key is working correctly, there is some traffic
<img width="291" alt="zrzut ekranu 2017-06-10 o 12 22 27" src="https://user-images.githubusercontent.com/5656856/27002108-0381f232-4dd9-11e7-87e6-24f6f3b51da1.png">
For comparison, screenshot from iOS version
![simulator screen shot 10 06 2017 12 36 38](https://user-images.githubusercontent.com/5656856/27002148-9ec6e3e2-4dd9-11e7-9fd1-831d54d3c9c2.png)
Version I use:
```
"react-native-maps": "^0.13.0",
"react-native": "0.43.2",
```
And this is my `Map` component:
```
import React, {PropTypes} from 'react';
import {
  Text,
  View,
  TouchableOpacity
} from 'react-native';
import styles from './Map.style';
import * as Shapes from '../../Utils/Shapes';
import {
  LATITUDE_DELTA,
  LONGITUDE_DELTA
} from '../../Utils/Constants'
import dismissKeyboard from 'dismissKeyboard';
import MapView from 'react-native-maps';

const Map = (props) => {
  const createDescription = (lunch) => {
    return lunch.reduce((accumulator, currentValue, currentIndex) => {
      return currentIndex === 0 ? `${currentValue.price}zł, ${currentValue.desc}` : 
      `${accumulator}\n${currentValue.price}zł, ${currentValue.desc}`
    }, '');
  };

  const renderMarkers = () => {
    return (
      props.data.map((marker, index) =>
        <MapView.Marker
          coordinate={marker.coordinate}
          key={index}
        >
          {props.showCallout &&
            <MapView.Callout style={styles.callout}>
              <TouchableOpacity 
                onPress={() => {
                  props.handleCalloutPress(marker);
                }}
              >
              <View>
                <Text style={styles.calloutTitle}>
                  {marker.name}
                </Text>
                <Text
                  ellipsizeMode='tail'
                  numberOfLines={5}
                >
                {createDescription(marker.lunch)}
                </Text>
              </View>
              </TouchableOpacity>
            </MapView.Callout>
          }
        </MapView.Marker>
      )
    );
  }

  return (
    <View style={styles.container}>
      <MapView
        loadingEnabled={props.loadingEnabled}
        rotateEnabled={props.rotateEnabled}
        pitchEnabled={props.pitchEnabled}
        scrollEnabled={props.scrollEnabled}
        zoomEnabled={props.zoomEnabled}
        onPress={() => {
          dismissKeyboard();
          props.handlePress();
        }}
        style={styles.map}
        showsUserLocation={true}
        initialRegion={{
          ...props.region,
          latitudeDelta: LATITUDE_DELTA,
          longitudeDelta: LONGITUDE_DELTA
        }}
      >
        {renderMarkers()}
      </MapView>
    </View>
  );
};

Map.propTypes = {
  data: PropTypes.arrayOf(PropTypes.shape({
    name: PropTypes.string,
    coordinate: Shapes.coordinate.isRequired,
    lunch: Shapes.lunch
  })),
  region: Shapes.coordinate.isRequired,
  handleCalloutPress: PropTypes.func,
  handlePress: PropTypes.func,
  showCallout: PropTypes.bool,
  loadingEnabled: PropTypes.bool,
  rotateEnabled: PropTypes.bool,
  pitchEnabled: PropTypes.bool,
  scrollEnabled: PropTypes.bool,
  zoomEnabled: PropTypes.bool
};

Map.defaultProps = {
  handleCalloutPress: () => {},
  handlePress: () => {},
  loadingEnabled: true,
  rotateEnabled: true,
  pitchEnabled: true,
  scrollEnabled: true,
  zoomEnabled: true
}

export default Map;
``` 
No clue what can be problem here, it works on iOS like a charm. 

**Edit:** 
the same happens with version 
```
"react-native-maps": "^0.15.2",
```
I've also tried to run [this example](https://github.com/airbnb/react-native-maps/blob/master/example/examples/DefaultMarkers.js) with my configuration and here is result https://youtu.be/YSAke3T6fvo
💥

**Comment by BobaFaux** [comment] 2017-06-14 14:49
I have been having the exact same issue. I ended up reverting back to 0.15.0 and it works fine. Both 0.15.1 and 0.15.2 have this same issue.

**Comment by wonskarol** [comment] 2017-06-15 19:22
Thanks @BobaFaux! 
I can confirm, it works with 0.15.0 🎉
Is this known issue?

**Comment by heysailor** [comment] 2017-07-20 07:47
+1 This occured for me too, on RN 0.45.1 and RNM versions 0.15.3, 0.15.2....downgrading to 0.15.1 worked for me. Same behaviour as the images above, on a clean install.

If you're trying to fix this, setting an explicit dependency on 0.15.2 in package.json like so will do the trick: `"react-native-maps": "0.15.2"` and then `npm install` or `yarn install`.

Error logged repeatedly in emulator console:

`E/GLConsumer: [SurfaceTexture-0-14704-0] syncForReleaseLocked: error dup'ing native fence fd: 0x3000`

**Comment by lvntayn** [comment] 2017-08-04 01:32
I have same problem in 0.15.3 version.

Error: 
`[SurfaceTexture-0-5888-0] syncForReleaseLocked: error dup'ing native fence fd: 0x3000`

**Comment by heysailor** [comment] 2017-08-24 10:35
After a bit of bashing about, I've found this is caused by using an outdated GoogleMaps pod. I was using GoogleMaps 2.1.0. Running `pod update` in the `ios` folder instead of `pod install` does the trick. At the time of writing, the current version of GoogleMaps is 2.4.1.

**Comment by heysailor** [comment] 2017-08-24 12:18
After a lot of bashing about, I found that removing google play compilation from the grade dependencies fixed this.

In `app/build.gradle`:

    dependencies {
        ...
         compile "com.airbnb.android:react-native-maps:+"
    }

**Comment by Marswang92** [comment] 2017-09-14 05:59
Having the same issue right here, using `rnm 0.16.2` and `rn 0.48.3`

**Comment by TitanKing** [comment] 2017-09-15 14:38
Same issue on rn 0.47.2 and rnm 0.16.4

**Comment by TitanKing** [comment] 2017-09-15 19:18
I resolved this by doing this:
https://github.com/airbnb/react-native-maps/issues/1043

**Comment by rtman** [comment] 2017-11-05 04:06
I encountered this exact issue with with `RN 0.49.3` and `RNMaps 0.17.1`.

To add further info i saw a lot of this error in `logcat` whenever the map view was onscreen or i tried to interact with it while it was grey and after minimizing and pulling it back up (when it would show the map):

```
11-04 12:15:36.081  5754  5794 E GLConsumer: [SurfaceTexture-0-5754-2] syncForReleaseLocked: error dup'ing native fence fd: 0x3000
```

'Fixed' it by reverting to `0.15.0`, i had to modify `0.15.0` however as it had incompatibilities with the latest RN version due to breaking changes introduced (Proptypes and one @override).

I tried all the different options mentioned above but only reverting worked. Here's my dependencies for google play base and maps

```
    compile(project(':react-native-maps')){
        exclude group: 'com.google.android.gms', module: 'play-services-base'
        exclude group: 'com.google.android.gms', module: 'play-services-maps'
    }
    compile 'com.google.android.gms:play-services-maps:11.4.2'
    compile "com.google.android.gms:play-services-base:11.4.2"

```

Would be great to use the latest version of RNMaps tho, anyone have any ideas on how to get it working?

**Comment by heysailor** [comment] 2017-11-05 13:30
This happens when your google maps API key is invalid.

On 5 Nov 2017 3:06 pm, "rtman" <notifications@github.com> wrote:

I encountered this exact issue with with RN 0.49.3 and RNMaps 0.17.1.

To add further info i saw a lot of this error in logcat whenever the map
view was onscreen or i tried to interact with it while it was grey and
after minimizing and pulling it back up (when it would show the map):

11-04 12:15:36.081  5754  5794 E GLConsumer: [SurfaceTexture-0-5754-2]
syncForReleaseLocked: error dup'ing native fence fd: 0x3000

'Fixed' it by reverting to 0.15.0, i had to modify 0.15.0 however as it had
incompatibilities with the latest RN version due to breaking changes
introduced (Proptypes and one @override <https://github.com/override>).

I tried all the different options mentioned above but only reverting
worked. Here's my dependencies for google play base and maps

    compile(project(':react-native-maps')){
        exclude group: 'com.google.android.gms', module: 'play-services-base'
        exclude group: 'com.google.android.gms', module: 'play-services-maps'
    }
    compile 'com.google.android.gms:play-services-maps:11.4.2'
    compile "com.google.android.gms:play-services-base:11.4.2"


Would be great to use the latest version of RNMaps tho, anyone have any
ideas on how to get it working?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/airbnb/react-native-maps/issues/1399#issuecomment-341947678>,
or mute the thread

**Comment by rtman** [comment] 2017-11-06 01:08
@heysailor 

I'm fairly certain that is not the case since I could see my interactions with the Maps API in the dashboard while this issue was happening. So the key was functioning and I was communicating and receiving data from the server. Also i didn't change my API key at all when trouble shooting this, just react-native-maps version to 0.15.0 and it started working properly.

**Comment by heysailor** [comment] 2017-11-06 06:51
Apologies, I was on mobile and didn't check through the prior posts. Did
you try the Google Play services one-liner as I posted before?

Cheers

**Comment by aforty** [comment] 2017-12-08 19:56
I'm running into this too with the latest version. Has anyone figured out the cause or found a work-around for now? My app is essentially unusable on Android.

**Comment by aforty** [comment] 2017-12-08 20:46
Ok, I found the source of the bug. However, I'm not skilled enough in Android to know why this causes the issue or what this means but hopefully some of you can help figure it out.

The issue was introduced in this commit 7bba6f939f425865cf917fc3b65fdf63533dcbd1.

Specifically, this change, when rolled back on version 0.18.3 fixes the issue for me.
Anyone care to elaborate what this does, what the intension behind this change might have been, and why this is causing problems on our use cases?

```
// lib/android/src/main/java/com/airbnb/android/react/maps/AirMapView.java
-        if (contextHasBug(superContext)) {
+        if (!contextHasBug(appContext.getCurrentActivity())) {
+            superContext = appContext.getCurrentActivity();
+        } else if (contextHasBug(superContext)) {
```

**Comment by carlove60** [comment] 2017-12-08 20:58
@aforty I'm confused. What did you do, precisely, to make it work?

**Comment by aforty** [comment] 2017-12-08 21:00
@carlove60 

I changed this
```
       if (!contextHasBug(appContext.getCurrentActivity())) {
           superContext = appContext.getCurrentActivity();
       } else if (contextHasBug(superContext)) {
```

to this
```
        if (contextHasBug(superContext)) {
```

**Comment by aforty** [comment] 2017-12-08 21:05
That commit was supposed to fix #1225, #1161, and #453.

**Comment by carlove60** [comment] 2017-12-08 21:29
@aforty This also fixes this issue!! Thank you very much for finding this weird ass bug.

**Comment by alvelig** [comment] 2017-12-13 02:59
@aforty please PR

**Comment by alvelig** [comment] 2017-12-13 03:02
@christopherdro I'm a little bit confused. What shall we do here?

**Comment by aranda-adapptor** [comment] 2018-02-06 09:12
Came across this with `react-native@0.53.0` and `react-native-maps@0.19.0`. Seems like this issue is worse than the ones the offending change was meant to fix (#1225, #1161, and #453).

**Comment by rborn** [comment] 2018-02-06 11:52
@aranda-adapptor could you please try installing from git. 0.19.0 on npm doesn't have many fixes (still needs to be pushed).

**Comment by aranda-adapptor** [comment] 2018-02-07 00:51
@rborn I tested the current git master and the issue remains. Applying the change as mentioned by @aforty above does resolve the issue, but I'm not sure why.

As far as I can tell, the issue is that the map is simply not triggering RN to re-render when it should. You can pan the map, click on markers etc and nothing changes, but when you trigger a re-render by changing a different component, the map updates to be where you'd expect it to be.

If anyone wants to test the change and re-test the associated issues, it is here: https://github.com/Adapptor/react-native-maps#fix_1399

**Comment by yoieh** [comment] 2018-02-19 14:00
Having the same issue here: 

Thow im using: 

```
"react-native": "^0.50.4",
"react-native-maps": "^0.20.1",
```


```
E/GLConsumer: [SurfaceTexture-0-8734-0] syncForReleaseLocked: error dup'ing native fence fd: 0x3000
```

Works fine on real device but not in my emulater.

**Comment by codypearce** [comment] 2018-03-23 00:44
Same issue here

```
"react-native": "^0.51.0",
"react-native-maps": "0.20.1",
```
Shows a blank map on both a real device and emulator.

@aforty Solution seems to work, should this merged to master or is there a more long term solution?

**Comment by 0angelic0** [comment] 2018-05-01 15:13
Same issue here

```
"react": "16.3.2",
"react-native": "0.55.3",
"react-native-maps": "^0.21.0",
```

@aforty Solution still makes it work.

**Comment by HamiltonMultimedia** [comment] 2018-05-26 02:35
Same issue still...

    `"react": "16.3.1",`
    `"react-native": "0.55.3",`
    `"react-native-maps": "^0.21.0"`

@0angelic0 led me to @aforty 's solution which fixes it for me!

Here's some screenshots for visual aids. 

He changed:
##  `/node_modules/react-native-maps/lib/android/src/main/java/com/airbnb/android/react/maps/AirMapView.java`

# Before
![before](https://user-images.githubusercontent.com/24661651/40571647-d07880f4-606a-11e8-9a87-682bcbcd104d.png)

to this 

# After
![after](https://user-images.githubusercontent.com/24661651/40571652-dd7a7654-606a-11e8-976d-c6c86a934616.png)

**Comment by pohnean** [comment] 2018-06-18 08:48
I've just encountered this issue also.

Changing my emulator from x86_64 to x86 fixed the issue for me.

**Comment by Baskerville42** [comment] 2018-09-25 08:37
> Ok, I found the source of the bug. However, I'm not skilled enough in Android to know why this causes the issue or what this means but hopefully some of you can help figure it out.
> 
> The issue was introduced in this commit [7bba6f9](https://github.com/react-community/react-native-maps/commit/7bba6f939f425865cf917fc3b65fdf63533dcbd1).
> 
> Specifically, this change, when rolled back on version 0.18.3 fixes the issue for me.
> Anyone care to elaborate what this does, what the intension behind this change might have been, and why this is causing problems on our use cases?
> 
> When I undo the change below, `contextHasBug(superContext)` then returns false and therefore the function then return `superContext`. That seems to work and makes the map function as intended.
> 
> With the code below in place `!contextHasBug(appContext.getCurrentActivity())` returns true and `superContext` is then set to `appContext.getCurrentActivity()` which seems to render the map unusable.
> 
> Thoughts?
> 
> ```
> // lib/android/src/main/java/com/airbnb/android/react/maps/AirMapView.java
> -        if (contextHasBug(superContext)) {
> +        if (!contextHasBug(appContext.getCurrentActivity())) {
> +            superContext = appContext.getCurrentActivity();
> +        } else if (contextHasBug(superContext)) {
> ```

this solution work for me
I have the same issue

"react-native": "0.56.0",
"react-native-maps": "^0.21.0",

**Comment by agm1984** [comment] 2018-11-04 23:02
@pohnean 's solution worked for me. I didn't and I still don't like the solution directly modifying the library from node_modules.

solution for Mac OS Google maps working while Android is showing a blank screen. On mine, the map displayed when I rotated the device simulator, so it was some kind of problem with initial state. Whatever runs when you rotate the screen rrun some code that made the map display.

By default, it was blank like OPs image.

1. Go to Android Studio
2. Goto SDK manager
3. Download `Nougat x86` (not x86_64)
4. Make a new virtual device with that new image
5. Run it
6. `react-native run-android`
7. Success?

NOTE: Notice that I said `x86` and not `x8_64`. The issue probably has something to do with graphics rendering logic differences between 32bit and 64bit architecture.

Try @pohnean 's solution before you modify anything in the node_modules.  pohnean's solution is Occam's razer.

**Comment by rborn** [comment] 2019-01-18 14:33
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with [the latest stable version](https://github.com/react-native-community/react-native-maps/releases).

Thank you!

**Closed by rborn** 2019-01-18 14:33 UTC
