### ISSUE TITLE
AnimatedViews example: Zooming and moving around does not work

### ISSUE THREAD

**Issue by gorjanz** [react-native-community/react-native-maps#108] opened 2016-03-02 09:57 UTC
Why is the zooming and moving around in the map, not working in the example with the animated views => /examples/AnimatedViews.js

I am trying to build an app where the user can use the views in the bottom to see information about a marker, and jump to that marker depending on what view is in the middle, but I also need the possibility of the user zooming in, and seeing more details about the neighbourhood, roads that lead to the position of the marker, etc. For this, I need the zoom, rotate, move-around functionality, essential for the map view, and otherwise present in the other examples.

I tried including the zoomEnabled and scrollEnabled set to true, but this did not help. Is there something I am missing, or is this a missing functionality for the MapView.Animated view?

Otherwise, great work, appreciate it...

**Comment by kristianmandrup** [comment] 2016-03-03 15:33
I just tried running the `/example` project and the *Animated Views* is not working.

```bash
undefined is not a constructor
evaluating new Animated.Region({... })
```

`AnimatedViews @196:0`

ie. it fails here:

```js
      region: new Animated.Region({
        latitude: LATITUDE,
        longitude: LONGITUDE,
        latitudeDelta: LATITUDE_DELTA,
        longitudeDelta: LONGITUDE_DELTA,
      }),
```

Note that I upgraded to `"react-native": "0.20",` so maybe the API for `Animated` has changed? Very likely, since this is an area under development/improvement according to statements made at React Conf recently!

**Comment by gorjanz** [comment] 2016-03-03 20:31
Yeah, but I already did the patch, and changed the contents of AnimatedImplementation.js, with the one provided in this project, so Region is declared there, and usable. The example runs, and the functionality showcased by the example, works as expected. It's the basic functionality of the map that is lost.

**Comment by badasve** [comment] 2016-03-11 21:20
In the styles, comment the paddingTop property of itemContainer and uncomment the top property ;)

**Comment by kristianmandrup** [comment] 2016-03-12 10:32
@gorjanz What patch exactly? Do you have a working example with `Animated.Region` on github a gist or sth? Thanks :)

**Comment by badaz** [comment] 2016-03-12 13:36
It's in the docs "using with the Animated API" section I think, you have to replace a file with one provided by the author

**Comment by kristianmandrup** [comment] 2016-03-13 12:53
Ah yes this one [AnimatedImplementation.js]( https://gist.github.com/lelandrichardson/c0d938e02301f9294465)

**Comment by gorjanz** [comment] 2016-03-15 09:40
@kristianmandrup a bit late response, but, yes that was the file I was referring to.
@badasve Thanks, I will try this first chance I get, and close the issue if successful.

**Comment by mylonasg88** [comment] 2016-03-31 11:10
Hi,
I just had same error as @**kristianmandrup** so I followed and changed content of ```node_modules/react-native/Libraries/Animated/src/AnimatedImplementation.js``` (1695 lines of code where [this one](https://github.com/facebook/react-native/blob/master/Libraries/Animated/src/AnimatedImplementation.js) is 1904 and I believe am using the latest `react-native`)
with
[AnimatedImplementation.js](https://gist.github.com/lelandrichardson/c0d938e02301f9294465)

Now I am getting some new errors:
![screen shot 2016-03-31 at 12 09 24](https://cloud.githubusercontent.com/assets/7348544/14173992/6e5e7cc6-f739-11e5-9fc1-3fd02c195310.png)

Any ideas?

```
**dependencies**{
...
"react": "^0.14.8",
"react-native": "^0.22.2",
"react-native-maps": "^0.3.1"
}
```

**Comment by sasha42** [comment] 2016-04-01 08:25
I'm seeing a similar issue with the provided example. The commenting out solution from above did not work for me, and I don't quite understand how to use the AnimatedImplementation.js example.
![screen shot 2016-04-01 at 10 19 22](https://cloud.githubusercontent.com/assets/1775702/14201596/3a0a2424-f7f3-11e5-8704-6b7430a17951.png)
I ran `rnpm link`, the repository is up to date as of submitting this ticket, and here are my dependencies:
```
├── react@0.14.8
├── react-native@0.22.2
└── react-native-maps@0.3.1
```

**Comment by gorjanz** [comment] 2016-04-04 08:49
@sasha42 follow @badaz instructions to get it working. As for the actual example, I haven't gotten around to check if @badasve answer is working. If someone gets around to check it out, please close the issue if the fix is correct.

**Comment by mdutkin** [comment] 2016-04-09 21:33
guys, I had almost the same problem
<img width="374" alt="2016-04-10 0 27 12" src="https://cloud.githubusercontent.com/assets/8430504/14406534/0839b9fc-feb3-11e5-86c4-26f1c7eee259.png">
it was clear that the problem is in definition of `requestAnimationFrame`. I'm using `react-native@0.22.2`. I found the fix in one of the forks by @polacekpavel, which you can find in https://gist.github.com/polacekpavel/682bd75a54117516c166
line `var requestAnimationFrame = require('/fbjs/lib/requestAnimationFrame');` makes the deal.

**Comment by badaz** [comment] 2016-04-10 02:39
Tx ! Will try this asap !
guys, I had almost the same problem
<img width="374" alt="2016-04-10 0 27 12" src="https://cloud.githubusercontent.com/assets/8430504/14406534/0839b9fc-feb3-11e5-86c4-26f1c7eee259.png">
it was clear that the problem is in definition of `requestAnimationFrame`. I'm using `react-native@0.22.2`. I found the fix in one of the forks by @polacekpavel, which you can find in https://gist.github.com/polacekpavel/682bd75a54117516c166
line `var requestAnimationFrame = require('/fbjs/lib/requestAnimationFrame');` makes the deal.

---

**Comment by juand89** [comment] 2016-04-21 08:57
I followed @mdutkin instructions and changed the file but now I am having this issue:
![simulator screen shot apr 21 2016 5 56 19 pm](https://cloud.githubusercontent.com/assets/17539365/14703361/6f18f3be-07ea-11e6-92dc-8fc62fb8a81a.png)

**Comment by mdutkin** [comment] 2016-04-23 15:33
@juand89 try to `watchman watch-del-all` and restart your project in XCode, maybe this will help

**Comment by polacekpavel** [comment] 2016-04-24 08:36
@juand89 If `watchman watch-del-all` doesn't help try this revision [https://gist.github.com/polacekpavel/682bd75a54117516c166/43bc8173dd1ad8a58b074aebafe9f1efee4711fc](url)

**Comment by juand89** [comment] 2016-04-25 01:59
@polacekpavel watchman watch-del-all didn't help, can you pass me that revision again? it seems like the link is broken

**Comment by polacekpavel** [comment] 2016-04-25 06:56
Sry, try this [Tweaked AnimatedImplementation](https://gist.github.com/polacekpavel/682bd75a54117516c166/43bc8173dd1ad8a58b074aebafe9f1efee4711fc)

**Comment by juand89** [comment] 2016-04-26 01:18
@polacekpavel Thank you is finally working!!

**Comment by mdutkin** [comment] 2016-04-28 01:21
guys, after upgrading to RN 0.25.1 I'm having ass pain again..... buuuut, the fix is here 
https://gist.github.com/mdutkin/bb9a1beab88001cf48b087ef48a27be5
don't know if anyone having the same issues, but I suggest it would be better to leave it here)

**Comment by arthurnn** [comment] 2016-07-14 03:00
![screenshot 2016-07-13 22 59 04](https://cloud.githubusercontent.com/assets/833383/16826708/6be588e8-494d-11e6-881e-08bdea230d86.png)
Getting that error, I think it is related to this issue.

my package.json
```
  "dependencies": {
    "react": "15.2.1",
    "react-native": "0.29.0",
    "react-native-maps": "^0.7.1"
  }
```

So what is the fix for this? patch RN ?

**Comment by nazywamsiepawel** [comment] 2016-08-10 15:59
+1, same issue with RN 0.31

**Comment by polacekpavel** [comment] 2016-08-10 18:36
@nazywamsiepawel can you try this? [animatedImplementation](https://gist.github.com/polacekpavel/682bd75a54117516c166)

**Comment by fdnhkj** [comment] 2016-08-15 16:38
Anyone knows if there is an issue or PR in react-native repo about this issue ?
It would be great to get a proper fix for this instead of modifying that file.

**Comment by JoshM1994** [comment] 2016-08-15 21:37
> @nazywamsiepawel can you try this? animatedImplementation

I tried the new file and still have no functionality on the map (i.e. no zooming, scrolling etc.)

**Comment by radek1991** [comment] 2016-08-23 13:25
@polacekpavel  your fix work for me RN 0.31 thx man :)

**Comment by khanhdd83** [comment] 2016-09-13 10:39
Errror update AnimatedImplementation.js
<img width="386" alt="screen shot 2016-09-13 at 17 38 28" src="https://cloud.githubusercontent.com/assets/7984350/18470861/f0572346-79d8-11e6-9dec-1e5efcea2e46.png">

**Comment by mjsisley** [comment] 2016-09-28 03:24
Running the example (RN 0.32) gives the above error. @polacekpavel Your version appears to work on RN 0.31, do you have any advice on how to approach solving the issue?

**Comment by khanhdd83** [comment] 2016-09-28 04:46
I changed the function run

**Comment by mjsisley** [comment] 2016-09-28 23:18
@khanhdd83 Thanks! Would you be willing to post the updated code?

**Comment by mjsisley** [comment] 2016-09-29 00:37
Nevermind, got it.

**Comment by tonygriv** [comment] 2016-10-11 06:56
How can I update animatedImplementation.js correctly?

**Comment by RWOverdijk** [comment] 2016-10-30 14:56
Any updates on this?

**Comment by Rpaixao** [comment] 2016-12-04 15:58
+1

**Comment by davinanaya** [comment] 2017-01-04 04:05
[
![capture](https://cloud.githubusercontent.com/assets/19170814/21631408/f41d9518-d208-11e6-8088-aa9467f54fd2.PNG)
](url)

`region: new Animated.Region({
				latitude: latitude,
				longitude: longitude,
				latitudeDelta: LATITUDE_DELTA,
				longitudeDelta:LONGITUDE_DELTA
			}),`
but when i remove the animated work fine

**Comment by SjoerdvGestel** [comment] 2017-02-06 09:12
Im using AnimatedRegion and MapView.Animated but no animation to speak off when changing the region

**Comment by tenya** [comment] 2017-02-17 01:41
i have the some problem in RN 0.40 ,Genymotion android 6.0,who can help me ?
![Uploading image.png…]()
![Uploading QQ截图20170216173400.png…]()

**Comment by moritzschaefer** [comment] 2017-05-05 10:53
@badasve while your approach fixes the touch events for the map, unfortunately moving the Marker-Views won't overlap the map anymore

**Comment by badasve** [comment] 2017-05-07 10:20
Sorry about that, I did not have this use case to handle

**Comment by moritzschaefer** [comment] 2017-05-07 16:28
All right. For everyone else who DOES have that use case, I did the following:

- Add the property pointerEvents=none to the View which is on the same level as the MapView:
```
          </MapView.Animated>
          <View style={[styles.itemContainer]}
            pointerEvents={'none'}
          >
          ...
```
- When the PanController accepts a gesture (onPanResponderGrant), change the value of your MapView so that it won't react on gesture inputs. These are the properties you have to set on your PanController

```
          onPanResponderGrant={this.onPanControllerGrant}
          onRelease={this.onPanControllerRelease}
```

**Closed** 2019-01-17 09:21 UTC
