### ISSUE TITLE
Android MapView.Marker bug

### ISSUE THREAD

**Issue by amereii** [react-native-community/react-native-maps#2357] opened 2018-07-03 08:27 UTC
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?
Yes

### Environment

Environment:
  OS: Windows 10
  Node: 8.1.3
  Yarn: 1.6.0
  npm: 5.0.3
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.1.0.0 AI-173.4697961

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.2 => 0.55.2

**react-native-maps : 0.21.0**

### Steps to Reproduce

```bash
git clone https://github.com/RooyeKhat-Media/iGap-Plus.git
cd iGap-Plus
react-native run-android
```

### Expected Behavior

On iOS everything is OK , You can see user's avatar , On android sometimes it works and sometimes not works
![image](https://user-images.githubusercontent.com/16239920/42207303-e3cfa994-7ebe-11e8-8e1d-c8f30aee5bea.png)

Our map marker , uses `Avatar` object  ,  https://github.com/RooyeKhat-Media/iGap-Plus/blob/master/src/components/MainTabs/Nearby/Map/MapMarker/index.js#L35 

### Actual Behavior

You can see that some avatars are blank (Image is not displayed)
![image](https://user-images.githubusercontent.com/16239920/42207683-c20b67f2-7ebf-11e8-9a04-30e98b73e9a2.png)

### Reproducible Demo

https://github.com/RooyeKhat-Media/iGap-Plus

Nearby Sources : 
https://github.com/RooyeKhat-Media/iGap-Plus/tree/master/src/components/MainTabs/Nearby
https://github.com/RooyeKhat-Media/iGap-Plus/blob/master/src/screens/MainTabs/NearbyScreen.js

**Comment by markmssd** [comment] 2018-07-23 03:02
Having the same issue with icons, have you found a solution?

**Comment by amereii** [comment] 2018-07-23 06:07
@markmssd NO

**Comment by cdra0624** [comment] 2018-07-28 03:39
@amereii 
same here. I'm trying to find solution...

on my case, 
```
<MapView.Marker
   image={IMAGE_SOURCE} >
```

works, but I want to use `Image` ...

**Comment by Billy-** [comment] 2018-07-30 16:33
Pretty sure this is an exact duplicate of #1870

**Closed** 2020-03-04 21:43 UTC
