### ISSUE TITLE
Is there a way to get the current region after fitToCoordinates?

### ISSUE THREAD

**Issue by kenma9123** [react-native-community/react-native-maps#1591] opened 2017-08-24 14:16 UTC
I'm having a difficulty getting the right deltas on two points(marker). Everytime I use `fitToCoordinates` on certain points and fire a `setState` to rerender. The old region is getting rerendered on the `mapView`.

I want to able to update the `region` state of my app everytime I call the `fitToCoordinates`.

Is there a way to get the current region progmatically? I know there's a prop on the `mapview` about `onRegionChange` but this only happens when you interact on the map not when you call a method like the `fitToCoordinates`

**Comment by IjzerenHein** [comment] 2017-10-17 20:31
This should be fixed by PR #1710

**Comment by supryan** [comment] 2019-01-15 00:31
+1

**Comment by christopherdro** [comment] 2019-01-17 09:17
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/react-native-community/react-native-maps/releases).

Thank you!

**Closed by christopherdro** 2019-01-17 09:17 UTC
