### ISSUE TITLE
[Android] Navigating between two maps makes the markers jump

### ISSUE THREAD

**Issue by proProbe** [react-native-community/react-native-maps#984] opened 2017-01-20 13:09 UTC
Hello everyone!

Im currently having huge issues where the markers jump around when you change from one map to another through navigation. What happens is that when I change scene (thus changing to a differnt map), the markers on the second map starts to freak out and jump around a lot.

Code can be seen below.

My first map looks like this:
```
                    <MapView
                        style={styles.map}
                        ref={this._setMapRef}
                        onPress={this._onPressMap}
                        onRegionChange={this._onRegionChange}
                        onRegionChangeComplete={this._onRegionChangeComplete}
                        rotateEnabled={false}
                        showsUserLocation={true}
                        showsMyLocationButton={false}
                        toolbarEnabled={false}
                        moveOnMarkerPress={Platform.OS === "android" ? false : undefined}
                    >
                        {this._renderMarkers()}
                    </MapView>
```
My second map looks like this:
```
                <MapView
                    ref={ref => { this.map = ref; }}
                    style={{
                        position: "absolute",
                        top: 0,
                        left: 0,
                        right: 0,
                        bottom: 0,
                    }}
                    initialRegion={region}
                    showsMyLocationButton={false}
                    toolbarEnabled={false}
                    rotateEnabled={false}
                    showsUserLocation={true}
                    moveOnMarkerPress={Platform.OS === "android" ? false : undefined}
                >
                    {/* { this._renderMarkers(posts) } */}
                    <MapView.Marker
                            coordinate={{
                                latitude: 30,
                                longitude: 30,
                            }}
                        >
                    </MapView.Marker>
                    <MapView.Marker
                            coordinate={{
                                latitude: 31,
                                longitude: 31,
                            }}
                        >
                    </MapView.Marker>
                    <MapView.Marker
                            coordinate={{
                                latitude: 32,
                                longitude: 32,
                            }}
                        >
                    </MapView.Marker>
                    <MapView.Marker
                            coordinate={{
                                latitude: 33,
                                longitude: 33,
                            }}
                        >
                    </MapView.Marker>
                    <MapView.Marker
                            coordinate={{
                                latitude: 34,
                                longitude: 34,
                            }}
                        >
                    </MapView.Marker>
                </MapView>
```

Does anyone have a similar problem?

**Comment by slaterJJ** [comment] 2017-01-20 16:05
I am building an app with the exact same issue

**Comment by proProbe** [comment] 2017-01-23 10:32
Im currently setting the android map to `liteMode` to somehow have a map on the scene. This isnt ideal and I would love to know how to fix this bug :)

**Comment by vjeranc** [comment] 2017-01-24 16:32
This seems to happen with pure android.

http://stackoverflow.com/questions/37743929/two-mapviews-in-one-android-activity-jumping-flickering-markers

Might be incorrect usage of API or just a bug in the API itself.

iOS doesn't have that problem.

If you don't need both maps displayed just move the region away from the markers (increase zoom so no markers are displayed or shift a region to atlantic ocean or whatever), and when it's displayed change the region again.

**Comment by proProbe** [comment] 2017-01-27 09:20
@vjeranc this workaround kinda works. Im using this right now but realised that it doesnt work that well in the case of multiple maps (maps > 2)

**Comment by vjeranc** [comment] 2017-01-27 09:48
@proProbe yes, if you have to display more than one map at the same screen it won't. but if you have different views (tabs or card stack), then the trick will prevent markers from jumping.

I've tried it with tab separated 3 map views and see no jumping (displaying efficiently more than 100 markers on each).

**Comment by proProbe** [comment] 2017-01-27 09:52
@vjeranc hm... how are you getting it to work? Im currently having 3 maps that all can have markers. If map1 needs to show its marker, doesnt it mean that both map2 and map3 needs to zoom and hide their markers?

**Comment by vjeranc** [comment] 2017-01-27 10:26
@proProbe of course. both `map2` and `map3` need to zoom (I move them to atlantic). I keep track of the tab state. `[false, true, false]` means the `tab2` is displayed (`map2` is on the `tab2`). when I change the tab the state changes and the two changed tab states (one changed from `false` to `true` and the other from `true` to `false) rerender both maps with newly calculated regions (markers are still in the DOM but not visible on the map).

**Comment by proProbe** [comment] 2017-01-28 11:40
@vjeranc sounds like a temporary solution. I will check it out! Might be a bit too complicated for my scenario as I might have multiple scenes with maps. I guess that the scenes should hide their maps somehow if they are unmounted or something

**Comment by vjeranc** [comment] 2017-01-28 11:53
@proProbe the problem shouldn't exist if scenes are unmounted because the map is unmounted as well. if you're using navigation card stack or similar, the whole stack is mounted.

although, mounting and unmounting of map is not very fast, so a better solution is just to have a `displayed` field for each scene and render the map with a particular region if the scene is displayed or not.

it's definitely a temporary solution.

**Comment by natalia-scr** [comment] 2017-02-06 17:14
For my project I am I rendering markers on a map. There is an option to generate new random markers whilst on the map which changes all the current markers appearing. When I do this option there is no a problem. However, if I navigate away from the map and return the markers will start to jump around.  I am using react native's built in navigator. This problem only occurs on android. I have tried switching the map to lite mode but the issue still persists.

**Comment by vjeranc** [comment] 2017-04-29 11:14
This is sill an issue, even with newer version of Google Maps for Android.

**Comment by natalia-scr** [comment] 2017-04-29 15:29
The issue was solved in my case. We had our navigator pushing screens on top on each other so no screen was actually closing. Fixed it by using replace instead of push with our react Navigator

**Comment by rborn** [comment] 2019-01-18 11:44
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/react-native-community/react-native-maps/releases).

Thank you!

**Closed by rborn** 2019-01-18 11:44 UTC

**Comment by royken** [comment] 2019-06-05 08:00
Hello, I am having the same issue here with my project. I am using 0.24.2 version of react-native-map @rborn

**Comment by chris-topher19** [comment] 2019-09-30 06:43
Still facing the issue

**Comment by acharyavikalp** [comment] 2020-02-26 10:43
It's also in React-native 0.61.5 same problem

**Comment by MedElba** [comment] 2021-06-25 19:31
Hello, I am having same issue with React native 0.63 and newest react-native-maps release (0.28). 
I have multiple screen with map in my tab navigator (never a screen with more than 1 map) but if in different tabs there are screens mounted with a map I have this continuous marker jumping! Can you reopen this issue??
