### ISSUE TITLE
rnpm is deprecated

### ISSUE THREAD

**Issue by JonnyBurger** [react-native-community/react-native-maps#2945] opened 2019-07-06 12:15 UTC
# Bug

In Version 0.60 of React Native, it gives a warning about the `rnpm` field in package.json.

```
warn The following packages use deprecated "rnpm" config that will stop working from next release:
  - react-native-maps: https://npmjs.com/package/react-native-maps
Please notify their maintainers about it. You can find more details at https://github.com/react-native-community/cli/blob/master/docs/configuration.md#migration-guide.
```

## Environment info
```
React native info output:

System:
    OS: macOS 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
    Memory: 21.65 MB / 8.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.13.0 - /usr/local/bin/node
    Yarn: 1.15.2 - ~/.yarn/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    Android SDK:
      API Levels: 23, 25, 26, 27, 28
      Build Tools: 23.0.1, 23.0.2, 23.0.3, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.0, 26.0.1, 26.0.3, 27.0.2, 27.0.3, 28.0.3
      System Images: android-25 | Google APIs Intel x86 Atom, android-26 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
  npmPackages:
    react: ^16.8.6 => 16.8.6
    react-native: ^0.60.0-rc.2 => 0.60.0-rc.2
  npmGlobalPackages:
    create-react-native-app: 2.0.2
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.4
```

## Steps To Reproduce

1. Create a new React native app with RN60
2. Add React Native Maps
3. Run npm start
...

Describe what you expected to happen:

No warning

**Comment by rborn** [comment] 2019-07-08 14:58
Can you please update following the template?

**Comment by jdegger** [comment] 2019-07-09 09:08
@rborn That wouldn't really be necessary right? The error is clear and it exists on all versions.

https://github.com/react-native-community/react-native-maps/blob/master/package.json#L56-L60
```json
"rnpm": {
    "android": {
      "sourceDir": "./lib/android"
    }
}
```

becomes react-native.config.js

```javascript
module.exports = {
  project: {
    ios: {},
    "android": {
      "sourceDir": "./lib/android"
    }
  },
};
```

**Comment by rborn** [comment] 2019-07-09 09:15
@jdegger I don't want to demotivate anyone, I just try to make people understand that their time is as valuable as ours the maintainers. Usually I just close the issue without asking for a template update.

We'll try to implement a bit that will make an initial filtering of the  issues, and then any issue that won't have a template will be closed automatically.

Makes any sense?

**Comment by jdegger** [comment] 2019-07-09 09:17
I does make sense, this is probably not the place for this discussion but I get where you are coming from. I think the world of GitHub issues might do well by having more human touch involved with looking at issues. However I do understand the amount of absolute garbage that comes in.

Anyway, thanks for your work on the plugin, it can not go unsaid that this is highly appreciated.

**Comment by JonnyBurger** [comment] 2019-07-09 11:12
Sorry, updated the issue with the proper template!

**Comment by rborn** [comment] 2019-07-09 11:13
@JonnyBurger amazing, thank you 🤗

**Comment by andersryanc** [comment] 2019-07-25 01:59
Looks like there is a PR for this: https://github.com/react-native-community/react-native-maps/pull/2975

**Comment by AmeerHamzaRiaz** [comment] 2019-08-10 07:29
Hi, I'm also facing this issue, on react-native-maps 0.25.0. How can upgrade it to the mentioned PR ?

**Comment by LeoMoreira1** [comment] 2019-08-15 17:37
im with the issue on react-native-maps 0.25.0 too

**Comment by kmvbatista** [comment] 2019-08-24 23:16
Hi. Does anybody know how to fix this issue?

**Comment by abegehr** [comment] 2019-08-25 20:51
The problem is that the PR was merged, but no new version of the package was released as of now. The latest version is 0.25.0 released on July 11, while the PR was after that end of July.
@rborn @andersryanc I'm looking forward to a new release soon – thank you!

**Comment by Javi** [comment] 2019-09-17 21:35
Is there a reason there's been no release so far?

**Comment by RWOverdijk** [comment] 2019-09-23 14:42
Maybe because of react native and cocoapods messy love story. 😄

**Comment by syaifulamir** [comment] 2019-09-24 17:01
+1

**Comment by SpertsyanKM** [comment] 2019-10-03 09:39
Release 0.26.0 fixes issue - https://github.com/react-native-community/react-native-maps/releases/tag/v0.26.0. 

This issue can be closed.

**Closed** 2019-10-03 13:24 UTC
