### ISSUE TITLE
showsUserLocation doesnt work on Android

### ISSUE THREAD

**Issue by Aid19801** [react-native-community/react-native-maps#2747] opened 2019-03-17 05:22 UTC
### Is this a bug report?

yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

yes

### Environment

MacOS 10.13.6 high sierra

"react": "16.6.0-alpha.8af6728",
    "react-native": "0.55.4",
    "react-native-geolocation-service": "^2.0.0",
    "react-native-maps": "^0.23.0",

### Steps to Reproduce

Either clone my app github at the bottom or...

`create-react-native-app myproj`

`yarn add react-native-maps`

follow [build config for android steps`(https://github.com/react-native-community/react-native-maps/blob/master/docs/installation.md#user-content-build-configuration-on-android)

use project wide dependencies

add key to `AndroidManifest.xml`

follow `import com.airbnb.android.react.maps.MapsPackage;` steps

put MapView into you RN component and change `showsUserLocation` to true.

build and run app 

My MapView is as follows:-

```
    <MapView
        provider={PROVIDER_GOOGLE}
        followsUserLocation={true}
        showsUserLocation={true}
        showsMyLocationButton={true}
        showsCompass={true}
        toolbarEnabled={true}
        zoomEnabled={true}
        rotateEnabled={true}
        
        style={{flex: 1}}
        region={{
        latitude: 51.4718,
        longitude: -0.0749,
        latitudeDelta: 0.01,
        longitudeDelta: 0.01
        }}
    >
        { markers.map((each, i) => {
            console.log('each: ', each);
            return ( 
                <MapView.Marker
                    key={i}
                    title={each.title}
                    description={each.description}
                    coordinate={{ latitude: each.latitude, longitude: each.longitude }}
                    />
            )
        }) }
    </MapView>
```

### Expected Behavior

Shows users location, a button to re-center the map on users location etc.

### Actual Behavior

Android Looks Like This:
no user location, no re-centering button, no compass, no toolbar (?) etc. These props dont seem to work at all, but most importantly the userLocation = 😭

![image](https://user-images.githubusercontent.com/15033409/54485523-ffb3f980-4871-11e9-84ab-00710ddc02e8.png)

Meanwhile, Xcode looks like this:
![image](https://user-images.githubusercontent.com/15033409/54485525-0a6e8e80-4872-11e9-82eb-61dfdb11775b.png)

(note Xcode's userLocation is manually set by me uploading .gpk file into xcode)

Documentation makes no mention of extra steps for Android so assumed it as just the `showsUserLocation` bool prop and emulator uses laptop location? If not, what other steps are necessary?

### Reproducible Demo

[Github repo here](https://github.com/Aid19801/that-history-app)

Other Things I've Tried:

- Emulator Settings: changed `location permissions` to *on* for this app.
- issue #209 / [link](https://github.com/react-native-community/react-native-maps/issues/209#issuecomment-350907665) - I can look to impl this as a last resort but i'd like confirmation that these props / this feature is not useable on Android first. Seems a pretty big hole in the proposition 😐
- loads of nuking of node modules, re-yarn'ing and re building etc. This is not a module / linking issue. Suspect it's something around Android Studio configuration or finding a way to send coords to the emulator like i did in Xcode. 

Help?

Thanks very much for your time and efforts on this project. 🤓

**Comment by jaysbytes** [comment] 2019-03-22 15:21
I faced a similar issue. Showing user location works out-of-the-box on iOS but not on Android. 
I found a workaround to ask for permissions using PermissionsAndroid module on map ready
```
<Map
  onMapReady={() => {
    PermissionsAndroid.request(
      PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION
    ).then(granted => {
      alert(granted) // just to ensure that permissions were granted
    }}
/>
```
Also don't forget to include permissions in `AndroidManifest.xml`
`<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />`

Ensure that GPS is enabled on your device/emulator. This solution shows the current location with a small delay.

If you want to show a button that you called "re-centering" you should use prop `showUserLocationButton`. I also faced issue with that, the button was not showing. The workaround was to force map re-render - check this related issue https://github.com/react-native-community/react-native-maps/issues/2010#issuecomment-427669285

**Comment by rborn** [comment] 2019-04-18 08:05
@Aid19801 you reacted with a 👍 so I assume it works for you therefore I'll close the issue.

**Closed by rborn** 2019-04-18 08:05 UTC

**Comment by ZaidSA** [comment] 2020-02-17 10:38
Expo:

```js
import * as Permission from 'expo-permissions'
```

Ask for location permission when needed,
```js
const { status } = await Permission.askAsync(Permission.LOCATION)
```
Once permission granted, then only `showsUserLocation` will work on Andoid.

**Comment by pbr0ck3r** [comment] 2020-05-05 17:34
> ```js
> <Map
>   onMapReady={() => {
>     PermissionsAndroid.request(
>       PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION
>     ).then(granted => {
>       alert(granted) // just to ensure that permissions were granted
>     });
>   }}
> />
> ```

Suggest checking the platform so as the Permission request does not try to fire on iOS.

> ```js
>  Platform.OS === 'android' ? PermissionsAndroid.request(
>       PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION) : ''
> ```

**Comment by dacsinu** [comment] 2020-12-01 03:31
So this did not work for me. Any other thoughts?

**Comment by MiguelNiblock** [comment] 2021-01-20 07:55
This is still a bug. This work-around fixed it for me. https://github.com/react-native-maps/react-native-maps/issues/3026#issuecomment-641192209
The issue is that the mapview won't display showsUserLocation, or showsMyLocationButton or zoomControlEnabled, even if you explicitly set them to true. BUT IT WILL show them if the mapview style is changed after the component loads.

**Comment by dacsinu** [comment] 2021-01-20 19:07
I gave it a try but the solution doesn't work with the way my project is set up. is there a cleaner way to achieve that?

**Comment by NastuzziSamy** [comment] 2021-04-24 10:57
`expo-permissions` will be deprecated in favor of `expo-location`: https://docs.expo.io/versions/latest/sdk/location/

**Comment by gaurav131** [comment] 2023-09-02 15:38
None of the above solution worked for me,
this is what worked: - 
`
import * as Location from "expo-location";

// put the below line in useEffect
Location.requestForegroundPermissionsAsync();
`

**Comment by nimsara1999** [comment] 2024-06-04 20:11
> None of the above solution worked for me, this is what worked: - ` import * as Location from "expo-location";
> 
> // put the below line in useEffect Location.requestForegroundPermissionsAsync(); `

This method worked.

**Comment by Michota** [comment] 2025-05-22 17:08
> None of the above solution worked for me, this is what worked: - ` import * as Location from "expo-location";
> 
> // put the below line in useEffect Location.requestForegroundPermissionsAsync(); `


Strange, it worked for a while, but then stopped.
