### ISSUE TITLE
fitToElements not working

### ISSUE THREAD

**Issue by sonnguyenit** [react-native-community/react-native-maps#1149] opened 2017-03-21 01:56 UTC
in `componentDidMount` i set `fitToElements(true)` but the map doesn't fit all markers to screen.
Here my code:
```
componentDidMount(){
		let _markers = [];
		for (let i = 0; i < this.props.locations.length; i++) {
			let _placeMarker = {
				coordinate : {
					latitude: this.props.locations[i].latitude,
					longitude: this.props.locations[i].longitude
				},
				title: this.props.locations[i].name,
				color: 'blue',
				key: i + 1
			};
			_markers.push(_placeMarker);
		};
		this.setState({
      region: {
        latitude: this.props.locations[0].latitude,
        longitude: this.props.locations[0].longitude,
        latitudeDelta: LATITUDE_DELTA,
        longitudeDelta: LONGITUDE_DELTA
      },
      markers: _markers
    });
    this.refs.map.fitToElements(true);
}
```
And in the render()
 ```
                            <View>
			      	<MapView
			        	ref="map"
			          provider={this.props.provider}
			          style={styles.map}
			          initialRegion={this.state.region}
			          loadingEnabled={true}
			          onPress={(e) => this.onMapPress(e)}
			        >
			          {this.state.markers.map(marker => (
			            <MapView.Marker
			              title={marker.title} 
			              key={marker.key}
			              coordinate={marker.coordinate}
			              pinColor={marker.color}
			            />
			          ))}
			        </MapView>
			      </View>
```
But my map screen only show the initialRegion marker, i must zoom out the map to show all markers
![map1](https://cloud.githubusercontent.com/assets/13761142/24129275/1a1fc49c-0e14-11e7-8064-f989c94ad6da.png)
I want to the map look like: 
![map2](https://cloud.githubusercontent.com/assets/13761142/24129282/2d7d8344-0e14-11e7-892d-f03a5bef26b8.png)

**Comment by fredjens** [comment] 2017-03-29 12:04
I have to same problem... But `fitToCoordinates` is working!

**Comment by sonnguyenit** [comment] 2017-03-30 01:59
@fredjens What is your code?
How do you use `fitToCoordinates` in your app.

**Comment by sytolk** [comment] 2017-07-23 14:19
@sonnguyenit check in this example:
https://github.com/airbnb/react-native-maps/blob/master/example/examples/FitToCoordinates.js

**Comment by sonnguyenit** [comment] 2017-08-02 10:56
@sytolk : I want to this app automatically fittocoordinates, not when press any button.

**Comment by sytolk** [comment] 2017-08-09 06:36
@sonnguyenit instead of press button you can have:
```xml
<MapView
 ref={(ref) => { this.mapRef = ref; }}
 onLayout={() => this.mapRef.fitToCoordinates(this.trip.coordinates, { edgePadding: { top: 50, right: 10, bottom: 10, left: 10 }, animated: false })} >
```

**Comment by krishbhattacharyya** [comment] 2017-08-18 08:08
@sonnguyenit  you should go through FitToSuppliedMarkers.js from given example folder.

On componentDidMount call this function-  ( if the markers are close to each other , it is working fine else the map can not Zoom out properly but it can reach your criteria  )
`focusMap(markers, animated) {
    	console.log(markers, animated)
	    console.log(`Markers received to populate map: ${markers}`);
	    this.map.fitToSuppliedMarkers(markers, animated);
}`

**Comment by GarimaMathur07** [comment] 2017-11-16 10:10
@sytolk When using fitToCoordinates, getting this error **not included points**
```
<MapView
 ref={(ref) => { this.mapRef = ref; }}
 onLayout={() => this.mapRef.fitToCoordinates(this.trip.coordinates, { edgePadding: { top: 50, right: 10, bottom: 10, left: 10 }, animated: false })} >
```
How can i fix this error

**Comment by sytolk** [comment] 2017-11-16 10:20
@GarimaMathur07 I suppose that you problem is that coordinates array is empty or with different mapping.
this is my coordinates type:
```
coordinates: ?TripLocation[]
type TripLocation = {
    tripId: string,
    timestamp: number,
    latitude: number,
    longitude: number
};
```

**Comment by GarimaMathur07** [comment] 2017-11-16 10:33
@sytolk Coordinate array is not empty but I am using this mapping and it gives me error  
```
let markers = [];
		for (let i = 0; i < this.props.locations.length; i++) {
			let placeMarker = {
				coordinate : {
					latitude: this.props.locations[i].latitude,
					longitude: this.props.locations[i].longitude
				},
				title: this.props.locations[i].name,
				key: i + 1
			};
			markers.push(placeMarker);
		};
```

```
<MapView
 ref={(ref) => { this.mapRef = ref; }}
 onLayout={() => this.mapRef.fitToCoordinates(this.markers.coordinate, { edgePadding: { top: 50, right: 10, bottom: 10, left: 10 }, animated: false })} >
```

**Comment by sytolk** [comment] 2017-11-16 10:38
try this
```
let markers = [];
		for (let i = 0; i < this.props.locations.length; i++) {
			let placeMarker = {
				latitude: this.props.locations[i].latitude,
				longitude: this.props.locations[i].longitude
				title: this.props.locations[i].name,
				key: i + 1
			};
			markers.push(placeMarker);
		};
<MapView
 ref={(ref) => { this.mapRef = ref; }}
onLayout={() => this.mapRef.fitToCoordinates(this.markers, { edgePadding: { top: 50, right: 10, bottom: 10, left: 10 }, animated: false })} >
```

**Comment by GarimaMathur07** [comment] 2017-11-16 10:46
@sytolk Thank you so much!! It is working fine now 👍

**Comment by clarktank** [comment] 2017-11-17 14:00
What is the status of this bug? 
My code works fine on iOS, as soon as my app loads, it fits all the markers on the screen. But on Android, the same code doesn't fit all the markers on the screen.
```
export default class MapScreen extends React.Component {

 componentDidMount() {
  this.map.fitToElements(true);
 }

 render() {
  return (
   <View style={styles.container}>

    <MapView
      ref={ref => { this.map = ref; }}
      region={this.state.region}
      style={{ flex: 1 }}
      onRegionChangeComplete={this._onRegionChangeComplete}
    >
      {places.map(place =>
       <MapView.Marker
         key={place.placetID}
         coordinate={{ latitude: place.lat, longitude: place.lng }}
         title={place.name}
         description={place.address}
        />
     )}
    </MapView>

    <View style={styles.button}>
     <Button
       onPress={() => this.map.fitToElements(true)} 
       title="Search Here"
       color="#841584" 
     />
    </View>

   </View>
  );
 }
}
```
For a workaround, I created a button with an onPress handler that calls:
`onPress={() => this.map.fitToElements(true)} `
So as soon as I press the button the map zooms out to fit all the markers, and it works on both iOS and Android.

The problem is the **componentDidMount** call on android. Has this been fixed? or does anyone know a workaround for it?

**Comment by codypearce** [comment] 2018-03-23 00:36
I am having the same issue as  @alvelig , `fitToSuppliedMarkers` works perfectly on iOS but fails on Android.

```
 componentDidMount() {

    this.mapRef.fitToSuppliedMarkers(
         ['hotel', '0'],
         false,
       );
  }
```

Using a timeout like @alvelig works as a quick fix for the time being, does anyone know of a more robust solution?

**Comment by W7PEA** [comment] 2018-09-05 01:37
I'm trying to determine if I'm seeing the same issue. 
Are you all seeing fitToElents _never_ work?

I am seeing it works on the first load of the map, but if I navigate away to a list view screen, change the map data, go back to the map, the map does not move to where the new markers are located. It does draw them though.

For comparison, this is my MapView component... 

    <MapView
      ref={(ref) => { this.mapRef = ref; }}
      style={{ flex: 1 }}
      mapType="standard"
      onLayout={() => {
      console.log("onLayout");
      this.mapRef.fitToElements(true);
      }}
    >

Thanks

**Comment by hszeto** [comment] 2019-04-01 07:51
ref works for me on both Android and iOS

```
<MapView
      ref={mapRef => mapRef===null ? null : mapRef.fitToElements(true) }
      style={styles.map}
      region={region}
      showsUserLocation
      showsMyLocationButton
>
      { this.renderMarkers() }
</MapView>
```

**Comment by rborn** [comment] 2019-04-01 08:51
closing as per https://github.com/react-native-community/react-native-maps/issues/1149#issuecomment-478473558

**Closed by rborn** 2019-04-01 08:51 UTC
Labels: Android, bug
