### ISSUE TITLE
Polyline

### ISSUE THREAD

**Issue by AlexChaseJones** [react-native-community/react-native-maps#1728] opened 2017-10-25 02:00 UTC
Polyline lineCap, lineJoin, and miterLimit properties have no effect on the rendering of the polyline from what I am seeing. May be an error on my end but seeing as the Docs are not accurate for these properties I'm guessing it's something to do with the codebase.

**Comment by JonasWho** [comment] 2017-12-18 12:16
I also can not get any effect of the miterLimit property and I have tons of issues with these kind of line spikes: 
![image](https://user-images.githubusercontent.com/925342/34105690-a1b5bcc4-e3f5-11e7-879e-9e3fa9b9e2be.png)

**Comment by JonasWho** [comment] 2017-12-18 12:20
@rborn I consider this a bug. Unless it's me not understanding the docs? :( 
It's only happening on iOS btw, on Android it looks fine.

**Comment by rborn** [comment] 2017-12-18 12:21
ios google maps or apple maps?

**Comment by rborn** [comment] 2017-12-18 12:23
@JonasWho Also could you provide an example on how to replicate the issue?

**Comment by JonasWho** [comment] 2017-12-18 12:42
I'm on RN 0.43.3 and I use the standard MapView with a Polyline showing the route generated by tracking the users trips. And these spikes are very frequent.

**Comment by rborn** [comment] 2017-12-18 12:52
It would still be good to have some code that reproduce this so if somebody is willing to look into it to have what to start with and not trying to find out how to reproduce

**Comment by JonasWho** [comment] 2017-12-18 13:36
@rborn turns out that if I set ``lineCap="round"`` on the Polyline, this spike behavior stops, which is weird, because the docs say, that ``round`` is the default value. Also, I would look into how the ``miter`` stuff works unde-the-hood if I had time, because as the docs describe, this should solve the problem, but it doesn't. 

Even better, would be an example of how to use these values and what difference they make. The existing docs are a bit hard to understand.

**Comment by rborn** [comment] 2017-12-18 13:39
Would you have time to look into? maybe check if `lineJoin` is indeed set to `round` by default and if not send a PR ?
As for the docs if you can come up with better things we're happy to merge.

**Comment by JonasWho** [comment] 2017-12-18 14:06
I think I found the spot where the default value was missing, made PR: https://github.com/react-community/react-native-maps/pull/1898

**Comment by sylvain75** [comment] 2018-01-11 01:24
@JonasWho
lineJoin="round" fixed also the spike behavior. Thanks

**Comment by ericjames** [comment] 2018-06-13 21:44
I'm seeing this problem too

**Comment by rborn** [comment] 2019-04-05 06:55
Closing as per https://github.com/react-native-community/react-native-maps/issues/1728#issuecomment-352434692 Please open a new issue if you still have this problem

**Closed by rborn** 2019-04-05 06:55 UTC
Labels: bug
