### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException Crash Error

### ISSUE THREAD

**Issue by lucasluca** [react-native-community/react-native-maps#3404] opened 2020-04-23 20:24 UTC
![image](https://user-images.githubusercontent.com/16627838/80145711-fe7df180-8586-11ea-9669-b087e5b73ddf.png)

"react-native": "0.62.2",
"react-native-maps": "0.27.1",

**Comment by samitha9125** [comment] 2020-04-23 20:27
@lucasluca Facing the same issue.

**Comment by harrigee** [comment] 2020-04-23 20:38
We are also experiencing issues with our production app right. Suddenly our bug tracking tool is going crazy since some minutes now.

"react-native": "0.61.5",
"react-native-maps": "0.27.1"

**Comment by jaredandrews** [comment] 2020-04-23 20:47
Also experiencing the same issue with:

"react-native": "0.62.2",
"react-native-maps": "^0.27.1",

**Comment by Alek-devsy** [comment] 2020-04-23 20:59
Same here..

```
04-23 22:55:49.653  4954  5019 E AndroidRuntime: FATAL EXCEPTION: androidmapsapi-ZoomTableManager
04-23 22:55:49.653  4954  5019 E AndroidRuntime: Process: com.randomApp, PID: 4954
04-23 22:55:49.653  4954  5019 E AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: length=1; index=12
04-23 22:55:49.653  4954  5019 E AndroidRuntime: 	at com.google.maps.api.android.lib6.gmm6.vector.ct.<init>(:com.google.android.gms.dynamite_mapsdynamite@200914068@20.09.14 (100700-0):9)
04-23 22:55:49.653  4954  5019 E AndroidRuntime: 	at com.google.maps.api.android.lib6.gmm6.vector.cv.a(:com.google.android.gms.dynamite_mapsdynamite@200914068@20.09.14 (100700-0):23)
04-23 22:55:49.653  4954  5019 E AndroidRuntime: 	at com.google.maps.api.android.lib6.gmm6.util.m.run(:com.google.android.gms.dynamite_mapsdynamite@200914068@20.09.14 (100700-0):14)
04-23 22:55:49.653  4954  5019 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
04-23 22:55:49.655  1897  2556 W ActivityManager:   Force finishing activity com.qpmobile/.MainActivity
04-23 22:55:49.668  1897  1912 I ActivityManager: Showing crash dialog for package com.qpmobile u0
```

iOS also crashes but works every 5-6 attempt

**Comment by davichoso** [comment] 2020-04-23 21:34
> UPDATE: This is not related to react-native-maps. Google maps is down as [this](https://outage.report/google-maps) says at 2020-04-23T20:31:00 GMT

Would You Say It's Time For Everyone To Panic?

**Comment by kceb** [comment] 2020-04-23 21:49
Also experiencing this same issue suddenly

**Comment by hutsi** [comment] 2020-04-23 21:49
same here

**Comment by LuisC360** [comment] 2020-04-23 21:53
Same here. It happened since an hour a half ago

`"react-native": "^0.62.2",
 "react-native-maps": "^0.27.0",`

**Comment by xn3cr0nx** [comment] 2020-04-23 22:12
Same here, this is actually really scary

**Comment by kubiisimsek** [comment] 2020-04-23 22:13
Same here.
`"react-native": "0.62.1","react-native-maps": "0.26.1"`

> java.lang.ArrayIndexOutOfBoundsException: length=1; index=12

**Comment by bbar** [comment] 2020-04-23 22:22
https://twitter.com/googlemaps/status/1253419390046834691

**Comment by sostenesg7** [comment] 2020-04-23 22:24
Me too. My production apps had stop working. :O

**Comment by drees** [comment] 2020-04-23 22:26
Upstream Google IssueTracker:
https://issuetracker.google.com/issues/154855417

**Comment by ManuEpi** [comment] 2020-04-23 22:26
Same here , it crash only in Android for me 

> "react-native": "0.61.4", "react-native-maps": "0.26.1"

**Comment by bbar** [comment] 2020-04-23 22:33
For me, the issue seems to be fixed now, but I had to uninstall, then reinstall. Are others experiencing this, or is your app "just working" again without a reinstall?

**Comment by cmdshepard** [comment] 2020-04-23 23:27
According to Google the issue is resolved, however it looks like you have to clear app data to get rid of a corrupted file to get your app working again.

Issue is referenced here -> https://issuetracker.google.com/issues/154855417

**Comment by ibrahimhuycn** [comment] 2020-04-24 02:17
I have been pulling my hair out because of this. I am on Xamarin forms. I could not find anything related to the error except here.

Clearing the app's data did the trick. Thanks @cmdshepard 

Java.Lang.ArrayIndexOutOfBoundsException: 'length=1; index=12'
FATAL EXCEPTION: androidmapsapi-ZoomTableManager

**Comment by gluons** [comment] 2020-04-24 07:05
Is there the error handler for preventing this problem in the future?

**Comment by moxorama** [comment] 2020-04-24 08:23
Is there any way to clear maps data from JS layer?

**Comment by DanGDroid** [comment] 2020-04-24 09:02
Google issue tracker suggests:
1. reinstall app
2. clear app Data
3. push a temp code fix to `Application.java` `onCreate`  ::
```java
 SharedPreferences googleBug = getSharedPreferences("google_bug_154855417", Context.MODE_PRIVATE);
        if (!googleBug.contains("fixed")) {
            File corruptedZoomTables = new File(getFilesDir(), "ZoomTables.data");
            corruptedZoomTables.delete();
            googleBug.edit().putBoolean("fixed", true).apply();
        }
solved for me  - no need of clear Data - but need an app update
[Google maps issue](https://issuetracker.google.com/issues/154855417#comment281)

**Comment by lfkwtz** [comment] 2020-04-24 12:11
@DanGDroid doing that same fix now -- did you put it at the bottom of the  `public void onCreate() {` method in MainApplication.java?

**Comment by lfkwtz** [comment] 2020-04-24 13:05
heads up to anyone else applying this fix, may need to add a couple imports

```
import android.content.SharedPreferences;
import java.io.File;
```

**Comment by DanGDroid** [comment] 2020-04-24 13:19
right after `super.onCreate()`
```java
import android.content.Context;
import android.content.SharedPreferences;
import java.io.File;
...
 @Override
  public void onCreate() {
    super.onCreate();
    SharedPreferences googleBug = getSharedPreferences("google_bug_154855417", Context.MODE_PRIVATE);
    if (!googleBug.contains("fixed")) {
        File corruptedZoomTables = new File(getFilesDir(), "ZoomTables.data");
        corruptedZoomTables.delete();
        googleBug.edit().putBoolean("fixed", true).apply();
    }
    AppEventsLogger.activateApp(this);
    SoLoader.init(this, /* native exopackage */ false);
  }
```

**Comment by edritech93** [comment] 2020-04-27 08:09
same for me

**Comment by vvusts** [comment] 2020-05-07 14:12
What is the status of this is this issue still possible?
Will this be implemented in this library?
I don't have this issue last few days so should I implement this fixes for ios/android or not?

**Comment by lfkwtz** [comment] 2020-05-07 14:22
@vvusts [fixed by Google](https://issuetracker.google.com/issues/154855417#comment509). basically - if you haven't patched it already - you won't need to. if you have, you can remove the patch.

**Closed** 2020-05-17 19:51 UTC
Labels: bug
